### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kevinsouthxu** [alpa-projects/alpa#383]
I got this error when I ran `python3 tests/test_install.py` after following the documented steps to install

```
.(raylet) /home/ubuntu/.local/lib/python3.9/site-packages/ray/dashboard/agent.py:163: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
(raylet)   if LooseVersion(aiohttp.__version__) < LooseVersion("4.0.0"):
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/pipeshard_parallel.py", line 325, in launch_func
    self._target(*self._args, **self._kwargs)
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/pipeshard_parallel.py", line 325, in launch_func
    physical_meshes[i] = virtual_meshes[i].get_physical_mesh()
  File "/home/ubuntu/alpa-proj/alpa/alpa/device_mesh.py", line 1360, in get_physical_mesh
    physical_meshes[i] = virtual_meshes[i].get_physical_mesh()
  File "/home/ubuntu/alpa-proj/alpa/alpa/device_mesh.py", line 1360, in get_physical_mesh
    return DistributedPhysicalDeviceMesh(
  File "/home/ubuntu/alpa-proj/alpa/alpa/device_mesh.py", line 791, in __init__
    self._launch_xla_servers()
  File "/home/ubuntu/alpa-proj/alpa/alpa/device_mesh.py", line 851, in _launch_xla_servers
    return DistributedPhysicalDeviceMesh(
  File "/home/ubuntu/alpa-proj/alpa/alpa/device_mesh.py", line 791, in __init__
    self.sync_workers()
  File "/home/ubuntu/alpa-proj/alpa/alpa/device_mesh.py", line 1066, in sync_workers
    self._launch_xla_servers()
  File "/home/ubuntu/alpa-proj/alpa/alpa/device_mesh.py", line 851, in _launch_xla_servers
    ray.get([w.sync.remote() for w in self.workers])
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    self.sync_workers()
  File "/home/ubuntu/alpa-proj/alpa/alpa/device_mesh.py", line 1066, in sync_workers
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/worker.py", line 1765, in get
    raise value
    ray.get([w.sync.remote() for w in self.workers])
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
ray.exceptions.RuntimeEnvSetupError: The runtime_env failed to be set up.
    return func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/worker.py", line 1765, in get
    raise value
ray.exceptions.RuntimeEnvSetupError: The runtime_env failed to be set up.
(raylet) /home/ubuntu/.local/lib/python3.9/site-packages/ray/dashboard/agent.py:163: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
(raylet)   if LooseVersion(aiohttp.__version__) < LooseVersion("4.0.0"):
(pid=gcs_server) [2022-04-12 04:45:56,590 E 8112 8112] (gcs_server) gcs_actor_scheduler.cc:320: The lease worker request from node 66dd38c2587d93376aa969420781c3120c5851ec71bdbdb72441809a for actor 1a30303eae247c52a029e37201000000(MeshHostWorker.__init__) has been canceled, job id = 01000000, cancel type: SCHEDULING_CANCELLED_RUNTIME_ENV_SETUP_FAILED
(pid=gcs_server) [2022-04-12 04:45:56,590 E 8112 8112] (gcs_server) gcs_actor_scheduler.cc:320: The lease worker request from node 66dd38c2587d93376aa969420781c3120c5851ec71bdbdb72441809a for actor cff1ce026d4a3d649ddc7d1801000000(MeshHostWorker.__init__) has been canceled, job id = 01000000, cancel type: SCHEDULING_CANCELLED_RUNTIME_ENV_SETUP_FAILED
E
======================================================================
ERROR: test_2_pipeline_parallel (__main__.InstallationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/alpa-proj/alpa/tests/test_install.py", line 127, in <module>
    runner.run(suite())
  File "/usr/lib/python3.9/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.9/unittest/case.py", line 651, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/home/ubuntu/alpa-proj/alpa/tests/test_install.py", line 112, in test_2_pipeline_parallel
    actual_state = parallel_train_step(state, batch)
  File "/home/ubuntu/alpa-proj/jax-alpa/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/ubuntu/alpa-proj/alpa/alpa/api.py", line 107, in ret_func
    compiled_func = parallelize_callable(
  File "/home/ubuntu/alpa-proj/jax-alpa/jax/linear_util.py", line 272, in memoized_fun
    ans = call(fun, *args)
  File "/home/ubuntu/alpa-proj/alpa/alpa/api.py", line 180, in parallelize_callable
    return pipeshard_parallel_callable(fun, in_tree, out_tree_thunk,
  File "/home/ubuntu/alpa-proj/jax-alpa/jax/linear_util.py", line 272, in memoized_fun
    ans = call(fun, *args)
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/pipeshard_parallel.py", line 204, in pipeshard_parallel_callable
    jp = DecentralizedDistributedRuntime(pipeline_stages=xla_stages,
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/decentralized_distributed_runtime.py", line 176, in __init__
    super().__init__(pipeline_stages=pipeline_stages,
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/base_runtime.py", line 122, in __init__
    self._establish_nccl_groups()
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/base_runtime.py", line 202, in _establish_nccl_groups
    self.physical_meshes.establish_nccl_group(i, j)
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/device_mesh_group.py", line 36, in establish_nccl_group
    device_strs = OrderedSet(src_mesh.device_strs + dst_mesh.device_strs)
jax._src.traceback_util.UnfilteredStackTrace: AttributeError: 'NoneType' object has no attribute 'device_strs'

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/alpa-proj/alpa/tests/test_install.py", line 112, in test_2_pipeline_parallel
    actual_state = parallel_train_step(state, batch)
  File "/home/ubuntu/alpa-proj/alpa/alpa/api.py", line 107, in ret_func
    compiled_func = parallelize_callable(
  File "/home/ubuntu/alpa-proj/alpa/alpa/api.py", line 180, in parallelize_callable
    return pipeshard_parallel_callable(fun, in_tree, out_tree_thunk,
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/pipeshard_parallel.py", line 204, in pipeshard_parallel_callable
    jp = DecentralizedDistributedRuntime(pipeline_stages=xla_stages,
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/decentralized_distributed_runtime.py", line 176, in __init__
    super().__init__(pipeline_stages=pipeline_stages,
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/base_runtime.py", line 122, in __init__
    self._establish_nccl_groups()
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/base_runtime.py", line 202, in _establish_nccl_groups
    self.physical_meshes.establish_nccl_group(i, j)
  File "/home/ubuntu/alpa-proj/alpa/alpa/pipeline_parallel/device_mesh_group.py", line 36, in establish_nccl_group
    device_strs = OrderedSet(src_mesh.device_strs + dst_mesh.device_strs)
AttributeError: 'NoneType' object has no attribute 'device_strs'

----------------------------------------------------------------------
Ran 2 tests in 50.506s

FAILED (errors=1)
(raylet) Traceback (most recent call last):
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/dashboard/agent.py", line 391, in <module>
(raylet)     loop.run_until_complete(agent.run())
(raylet)   File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
(raylet)     return future.result()
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/dashboard/agent.py", line 178, in run
(raylet)     modules = self._load_modules()
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/dashboard/agent.py", line 120, in _load_modules
(raylet)     c = cls(self)
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 161, in __init__
(raylet)     self._metrics_agent = MetricsAgent(
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/_private/metrics_agent.py", line 75, in __init__
(raylet)     prometheus_exporter.new_stats_exporter(
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/_private/prometheus_exporter.py", line 332, in new_stats_exporter
(raylet)     exporter = PrometheusStatsExporter(
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/_private/prometheus_exporter.py", line 265, in __init__
(raylet)     self.serve_http()
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/_private/prometheus_exporter.py", line 319, in serve_http
(raylet)     start_http_server(
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 168, in start_wsgi_server
(raylet)     TmpServer.address_family, addr = _get_best_family(addr, port)
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/prometheus_client/exposition.py", line 157, in _get_best_family
(raylet)     infos = socket.getaddrinfo(address, port)
(raylet)   File "/usr/lib/python3.9/socket.py", line 954, in getaddrinfo
(raylet)     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
(raylet) socket.gaierror: [Errno -2] Name or service not known
(raylet) 
(raylet) During handling of the above exception, another exception occurred:
(raylet) 
(raylet) Traceback (most recent call last):
(raylet)   File "/home/ubuntu/.local/lib/python3.9/site-packages/ray/dashboard/agent.py", line 407, in <module>
(raylet)     gcs_publisher = GcsPublisher(args.gcs_address)
(raylet) TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by zhuohan123** [comment]
Can you provide the spec of the cluster you are running on? For example, what's the CUDA and driver version? What's the OS you are installing things on? Are you running this on the cloud or an on-prem cluster? How many and what type of GPUs you are using?

**Comment by merrymercy** [comment]
This is similar to this issue https://github.com/alpa-projects/alpa/issues/377

**Comment by kevinsouthxu** [comment]
> Can you provide the spec of the cluster you are running on? For example, what's the CUDA and driver version? What's the OS you are installing things on? Are you running this on the cloud or an on-prem cluster? How many and what type of GPUs you are using?

The environment is:
Hardware: 4 NVIDIA Tesla V100 GPUs
Python:3.8
cuda:11.4
cudnn: cudnn-11.4-linux-x64-v8.2.4.15
And I'm  running this on a single machine with ubuntu20.04

**Comment by kevinsouthxu** [comment]
> This is similar to this issue [#377 (comment)](https://github.com/alpa-projects/alpa/issues/377#issuecomment-1093586840)

Thanks for your reply! I solve this problem by downloading nightly Ray wheels from [https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies](https://docs.ray.io/en/latest/ray-overview/installation.html#daily-releases-nightlies).
