### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by JiahaoYao** [alpa-projects/alpa#397]
**Please describe the bug**
`jaxlib` and `Jax` version is not compatible. 

**Please describe the expected behavior**

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): 18.04
- Python version: 3.8
- CUDA version: 11.6
- NCCL version: 2.11.4
- cupy version: 10.3.1
- GPU model and memory: 4 x T4
- Alpa version: 0.1.0
- TensorFlow version: 2.7.1
- JAX version: 0.3.5 (jax-alpa)

```python
(tensorflow2_p38) ubuntu@ip-10-0-1-112:~/alpa$ pip install -U jaxlib
Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Requirement already satisfied: jaxlib in /home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages (0.3.5)
Collecting jaxlib
  Using cached jaxlib-0.3.7-cp38-none-manylinux2014_x86_64.whl (68.5 MB)
Requirement already satisfied: numpy>=1.19 in /home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages (from jaxlib) (1.20.3)
Requirement already satisfied: scipy in /home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages (from jaxlib) (1.7.2)
Requirement already satisfied: absl-py in /home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages (from jaxlib) (1.0.0)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in /home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages (from jaxlib) (2.0)
Requirement already satisfied: six in /home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages (from absl-py->jaxlib) (1.16.0)
Installing collected packages: jaxlib
  Attempting uninstall: jaxlib
    Found existing installation: jaxlib 0.3.5
    Uninstalling jaxlib-0.3.5:
      Successfully uninstalled jaxlib-0.3.5
Successfully installed jaxlib-0.3.7
(tensorflow2_p38) ubuntu@ip-10-0-1-112:~/alpa$ python tests/test_install.py
Traceback (most recent call last):
  File "tests/test_install.py", line 6, in <module>
    from flax import linen as nn
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/flax/__init__.py", line 19, in <module>
    from . import core
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/flax/core/__init__.py", line 15, in <module>
    from .axes_scan import broadcast
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/flax/core/axes_scan.py", line 19, in <module>
    import jax
  File "/home/ubuntu/jax-alpa/jax/__init__.py", line 37, in <module>
    from jax import config as _config_module
  File "/home/ubuntu/jax-alpa/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/home/ubuntu/jax-alpa/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/ubuntu/jax-alpa/jax/_src/lib/__init__.py", line 87, in <module>
    version = check_jaxlib_version(
  File "/home/ubuntu/jax-alpa/jax/_src/lib/__init__.py", line 82, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib version 0.3.7 is newer than and incompatible with jax version 0.3.5. Please update your jax and/or jaxlib packages.
```

I find the jaxlib `0.3.7` does not work with the `Jax`. So, I downgraded the `jaxlib` to `0.3.5`. 

However, for the lower version of `jaxlib` (does not have `HloSharding`).

```python
(tensorflow2_p38) ubuntu@ip-10-0-1-112:~/alpa$ python tests/test_install.py
Traceback (most recent call last):
  File "tests/test_install.py", line 14, in <module>
    from alpa import (parallelize, set_parallelize_options, grad, global_config,
  File "/home/ubuntu/alpa/alpa/__init__.py", line 1, in <module>
    from . import api
  File "/home/ubuntu/alpa/alpa/api.py", line 18, in <module>
    from alpa.pipeline_parallel.local_pipeline_parallel import (
  File "/home/ubuntu/alpa/alpa/pipeline_parallel/local_pipeline_parallel.py", line 11, in <module>
    from alpa.device_mesh import PhysicalDeviceMesh
  File "/home/ubuntu/alpa/alpa/device_mesh.py", line 37, in <module>
    from alpa.shard_parallel.auto_sharding import LogicalDeviceMesh
  File "/home/ubuntu/alpa/alpa/shard_parallel/auto_sharding.py", line 515, in <module>
    hlo_sharding: xe.HloSharding, aval: ShapedArray,
AttributeError: module 'jaxlib.xla_extension' has no attribute 'HloSharding'
```

Appreciate it if someone know how to get around this issue!

**Comment by JiahaoYao** [comment]
Okay, fixed!

**Comment by JiahaoYao** [comment]
I am able to resolve the installation issue, but I have the following when running the test examples. 

```python
(tensorflow2_p38) ubuntu@ip-10-0-1-112:~/alpa$ python tests/test_install.py
2022-04-21 05:32:57.008529: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2143] Execution of replica 0 failed: INTERNAL: external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nccl_utils.cc:342: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: unhandled cuda error
2022-04-21 05:32:57.156551: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2143] Execution of replica 0 failed: INTERNAL: external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nccl_utils.cc:342: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: unhandled cuda error
2022-04-21 05:32:57.157654: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2143] Execution of replica 0 failed: INTERNAL: external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nccl_utils.cc:342: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: unhandled cuda error
2022-04-21 05:32:57.157879: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/pjrt_stream_executor_client.cc:2143] Execution of replica 0 failed: INTERNAL: external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nccl_utils.cc:342: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: unhandled cuda error
EE
======================================================================
ERROR: test_1_shard_parallel (__main__.InstallationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_install.py", line 127, in <module>
    runner.run(suite())
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "tests/test_install.py", line 78, in test_1_shard_parallel
    actual_state = parallel_train_step(state, batch)
  File "/home/ubuntu/jax-alpa/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/ubuntu/alpa/alpa/api.py", line 114, in ret_func
    out = compiled_func(*args_flat)
  File "/home/ubuntu/alpa/alpa/mesh_executable.py", line 715, in launch_on_driver
    grad_bufs = self.accumulate_grad.execute_sharded_on_local_devices(
jax._src.traceback_util.UnfilteredStackTrace: RuntimeError: INTERNAL: external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nccl_utils.cc:342: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: unhandled cuda error: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tests/test_install.py", line 78, in test_1_shard_parallel
    actual_state = parallel_train_step(state, batch)
  File "/home/ubuntu/alpa/alpa/api.py", line 114, in ret_func
    out = compiled_func(*args_flat)
  File "/home/ubuntu/alpa/alpa/mesh_executable.py", line 715, in launch_on_driver
    grad_bufs = self.accumulate_grad.execute_sharded_on_local_devices(
RuntimeError: INTERNAL: external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nccl_utils.cc:342: NCCL operation ncclCommInitRank(comm.get(), nranks, id, rank) failed: unhandled cuda error: while running replica 0 and partition 0 of a replicated computation (other replicas may have failed as well).

======================================================================
ERROR: test_2_pipeline_parallel (__main__.InstallationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_install.py", line 84, in test_2_pipeline_parallel
    ray.init(address="auto")
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/worker.py", line 1075, in init
    connect(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/worker.py", line 1486, in connect
    raise e
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/worker.py", line 1483, in connect
    node.check_version_info()
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/ray/node.py", line 364, in check_version_info
    raise RuntimeError(error_message)
RuntimeError: Version mismatch: The cluster was started with:
    Ray: 1.12.0
    Python: 3.6.9
This process on node 10.0.1.112 was started with:
    Ray: 1.12.0
    Python: 3.8.12


----------------------------------------------------------------------
Ran 2 tests in 7.728s

FAILED (errors=2)
```

**Comment by zhisbug** [comment]
It seems the error message tells that you have two ongoing Ray clusters; could you kill them and restart a single Ray cluster?

**Comment by JiahaoYao** [comment]
Thanks for ur prompt reply. Let me have a try.

**Comment by zhisbug** [comment]
@JiahaoYao is this issue resolved?

**Comment by JiahaoYao** [comment]
Thanks @zhisbug !
