### ISSUE TITLE
test_install.py failed due to jaxlib and jav version incompatibility 

### ISSUE THREAD

**Issue by RenfeiChen-FB** [alpa-projects/alpa#442]
**Please describe the bug**
Follow the installation tutorial, and every steps have been executed successfully. When I run the python tests/test_install.py, it shows 

```
Traceback (most recent call last):
  File "tests/test_install.py", line 6, in <module>
    from flax import linen as nn
  File "/home/renfeichen/.local/lib/python3.7/site-packages/flax/__init__.py", line 19, in <module>
    from . import core
  File "/home/renfeichen/.local/lib/python3.7/site-packages/flax/core/__init__.py", line 15, in <module>
    from .axes_scan import broadcast
  File "/home/renfeichen/.local/lib/python3.7/site-packages/flax/core/axes_scan.py", line 19, in <module>
    import jax
  File "/home/renfeichen/alpa/jax-alpa/jax/__init__.py", line 37, in <module>
    from jax import config as _config_module
  File "/home/renfeichen/alpa/jax-alpa/jax/config.py", line 18, in <module>
    from jax._src.config import config
  File "/home/renfeichen/alpa/jax-alpa/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/renfeichen/alpa/jax-alpa/jax/_src/lib/__init__.py", line 90, in <module>
    minimum_jaxlib_version=jax.version._minimum_jaxlib_version)
  File "/home/renfeichen/alpa/jax-alpa/jax/_src/lib/__init__.py", line 82, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib version 0.3.10 is newer than and incompatible with jax version 0.3.5. Please update your jax and/or jaxlib packages.
```

**Please describe the expected behavior**

It should succeed

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Ubuntu 18.04
- Python version: 3.7
- CUDA version: 11.1
- NCCL version: 2.10.3
- cupy version: 10.4.0
- GPU model and memory: Tesla V100 SXM2 16GB
- Alpa version: 0.0.0
- TensorFlow version: Didn't find it, only Tensorstore with 0.1.20
- JAX version: 0.3.5
- JAXLIB version: 0.3.10

**To Reproduce**
I followed every steps in https://alpa-projects.github.io/install/from_source.html#install-from-source

**Screenshots**

**Code snippet to reproduce the problem**

**Additional information**
I think the step to install javlib will install the version of 0.3.10, but the jax installation will give the version of 0.3.5.

**Comment by merrymercy** [comment]
This is fixed by https://github.com/alpa-projects/jax-alpa/commit/e93e6ed17b1310ad4e236b80371e79851642c830.
Please pull the latest `jax-alpa` and run Step 3 again

**Comment by merrymercy** [comment]
This is fixed by https://github.com/alpa-projects/jax-alpa/commit/22219884fdec81e8325cfe0de0cc0c627291f0a1.
Please start from step 3 again.
