### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by HachimiX** [alpa-projects/alpa#497]
Please describe the correct solution
When i run ```python3 build/build.py --enable_cuda --dev_install --tf_path=$(pwd)/../third_party/tensorflow-alpa```
it occurs an error: Every .bzl file must have a corresponding package

**System information and environment**
- OS: ubuntu 20.04
- Python: 3.8.10
- cuda: 11.1
- cudnn: 8.0.5

Error information:
```shell

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Bazel binary path: ./bazel-5.1.0-linux-x86_64
Bazel version: 5.1.0
Python binary path: /usr/bin/python3
Python version: 3.8
NumPy version: 1.22.4
MKL-DNN enabled: yes
Target CPU: x86_64
Target CPU features: release
CUDA enabled: yes
CUDA compute capabilities: 3.5,5.2,6.0,7.0,8.0
NCCL enabled: yes
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
./bazel-5.1.0-linux-x86_64 run --verbose_failures=true --config=avx_posix --config=mkl_open_source_only --config=cuda :build_wheel -- --output_path=/home/ubuntu/alpa-projects/alpa/build_jaxlib/dist --cpu=x86_64 --dev_install
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'run' from /home/ubuntu/alpa-projects/alpa/build_jaxlib/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /home/ubuntu/alpa-projects/alpa/build_jaxlib/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir.
INFO: Reading rc options for 'run' from /home/ubuntu/alpa-projects/alpa/build_jaxlib/.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env=PYENV_ROOT --python_path=/usr/bin/python3 --distinct_host_configuration=false --action_env TF_PATH=/home/ubuntu/alpa-projects/alpa/build_jaxlib/../third_party/tensorflow-alpa --action_env TF_NCCL_VERSION=2.8.4
INFO: Found applicable config definition build:short_logs in file /home/ubuntu/alpa-projects/alpa/build_jaxlib/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:avx_posix in file /home/ubuntu/alpa-projects/alpa/build_jaxlib/.bazelrc: --copt=-mavx --host_copt=-mavx
INFO: Found applicable config definition build:mkl_open_source_only in file /home/ubuntu/alpa-projects/alpa/build_jaxlib/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /home/ubuntu/alpa-projects/alpa/build_jaxlib/.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,7.0,8.0 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --define=xla_python_enable_gpu=true
INFO: Found applicable config definition build:cuda in file /home/ubuntu/alpa-projects/alpa/build_jaxlib/.jax_configure.bazelrc: --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,7.0,8.0
INFO: Found applicable config definition build:linux in file /home/ubuntu/alpa-projects/alpa/build_jaxlib/.bazelrc: --config=posix --copt=-Wno-stringop-truncation --copt=-Wno-array-parameter
INFO: Found applicable config definition build:posix in file /home/ubuntu/alpa-projects/alpa/build_jaxlib/.bazelrc: --copt=-fvisibility=hidden --copt=-Wno-sign-compare --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Found applicable config definition build:cuda in file /home/ubuntu/alpa-projects/alpa/build_jaxlib/.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,7.0,8.0 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --define=xla_python_enable_gpu=true
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: error loading package '': Every .bzl file must have a corresponding package, but '//third_party/pocketfft:workspace.bzl' does not have one. Please create a BUILD file in the same or any parent directory. Note that this BUILD file does not need to do anything except exist.
b''
Traceback (most recent call last):
  File "build/build.py", line 544, in <module>
    main()
  File "build/build.py", line 539, in main
    shell(command)
  File "build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bazel-5.1.0-linux-x86_64', 'run', '--verbose_failures=true', '--config=avx_posix', '--config=mkl_open_source_only', '--config=cuda', ':build_wheel', '--', '--output_path=/home/ubuntu/alpa-projects/alpa/build_jaxlib/dist', '--cpu=x86_64', '--dev_install']' returned non-zero exit status 2.
```

**Comment by JiahaoYao** [comment]
can u `ls ./bazel-5.1.0-linux-x86_64` to see whether there is this file ?

**Comment by HachimiX** [comment]
> can u `ls ./bazel-5.1.0-linux-x86_64` to see whether there is this file ?

It is solved by ``` git clone --recursive```
but i have an another question that doesn't have that much to do with it:
How do i reinstall tensorflow-alpa since i change something in tensorflow-alpa from source code

**Comment by zhisbug** [comment]
@HachimiX You can just recompile and reinstall via `pip install -e .` under `build_jaxlib/dist`

See the instruction here: https://alpa-projects.github.io/install.html#install-from-source

**Comment by HachimiX** [comment]
> @HachimiX You can just recompile and reinstall via `pip install -e .` under `build_jaxlib/dist`
> 
> See the instruction here: https://alpa-projects.github.io/install.html#install-from-source

Thanks for your reply!

**Comment by saisurbehera** [comment]
Did it work?
