### ISSUE TITLE
[potential error report] Minimal example of alpa  

### ISSUE THREAD

**Issue by JiahaoYao** [alpa-projects/alpa#509]
head import: 
```python
import ray
import numpy as np
from ray import tune
import alpa

ray.init()
alpa.init()
```

Example 1: 
```python
@alpa.parallelize
def func(a):
    return a

func(1.0)
```

Results
```python
2022-06-14 03:29:57,283 INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8266
Traceback (most recent call last):
  File "issue.py", line 16, in <module>
    func(1.0)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/api.py", line 103, in __call__
    out = executable.launch_on_driver(*args_flat)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/mesh_executable.py", line 310, in launch_on_driver
    input_uuids = (get_uuid_np_array(input_bufs).reshape(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/mesh_executable.py", line 216, in get_uuid_np_array
    shape = (len(array), len(array[0]))
IndexError: list index out of range
Exception ignored in: <function MeshDriverExecutable.__del__ at 0x7f44fb701040>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/mesh_executable.py", line 88, in __del__
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 1318, in delete_remote_executable
TypeError: 'NoneType' object is not callable
```

Example 2: 

```python 

import jax
from typing import Any, Callable, Sequence, Optional
from jax import lax, random, numpy as jnp
import flax
from flax.core import freeze, unfreeze
from flax import linen as nn

model = nn.Dense(features=5)


key1, key2 = random.split(random.PRNGKey(0))
x = random.normal(key1, (10,))  # Dummy input
params = model.init(key2, x)  # Initialization call


@alpa.parallelize
def jax_func(params, x):
    return model.apply(params, x)

print(jax_func(params, x))
```

Results:
```python
2022-06-14 03:32:21,397 INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8266
Traceback (most recent call last):
  File "issue.py", line 16, in <module>
    func(1.0)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/api.py", line 103, in __call__
    out = executable.launch_on_driver(*args_flat)
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/mesh_executable.py", line 310, in launch_on_driver
    input_uuids = (get_uuid_np_array(input_bufs).reshape(
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/mesh_executable.py", line 216, in get_uuid_np_array
    shape = (len(array), len(array[0]))
IndexError: list index out of range
Exception ignored in: <function MeshDriverExecutable.__del__ at 0x7fb910dde040>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/mesh_executable.py", line 88, in __del__
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 1318, in delete_remote_executable
TypeError: 'NoneType' object is not callable
```

Example 3: 

```python
import alpa
import numpy as np
import ray
from ray import tune

ray.init()
# alpa.init("ray")
alpa.init()


from typing import Any, Callable, Optional, Sequence

import flax
import jax
from flax import linen as nn
from flax.core import freeze, unfreeze
from jax import lax
from jax import numpy as jnp
from jax import random

model = nn.Dense(features=5)


key1, key2 = random.split(random.PRNGKey(0))
x = random.normal(key1, (10,2))  # Dummy input
params = model.init(key2, x)  # Initialization call

import alpa
import optax
from flax.training import train_state

cluster = alpa.get_global_cluster()
print("cpu", cluster.num_cpus)
print("gpu", cluster.num_devices)

@alpa.parallelize
def train_step(state, x):
    def loss_fn(params):
        loss = model.apply(params, x)
        return jax.numpy.sum(loss)

    grad_fn = jax.value_and_grad(loss_fn)

    loss, grads = grad_fn(state.params)
    state = state.apply_gradients(grads=grads)
    return state, loss


tx = optax.sgd(0.1)
state = train_state.TrainState.create(apply_fn=model.apply, params=params, tx=tx)
new_state, loss = train_step(state, x)

print(loss)
```

Result
```python
2022-06-14 03:33:24,242 INFO services.py:1477 -- View the Ray dashboard at http://127.0.0.1:8266
/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py:1866: UserWarning: Explicitly requested dtype <class 'numpy.float64'> requested in asarray is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  lax_internal._check_user_dtype_supported(dtype, "asarray")
cpu 4
gpu 1
-10.365741
Exception ignored in: <function MeshDriverExecutable.__del__ at 0x7fa6bf6f6040>
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/mesh_executable.py", line 88, in __del__
  File "/home/ubuntu/anaconda3/envs/tensorflow2_p38/lib/python3.8/site-packages/alpa/device_mesh.py", line 1318, in delete_remote_executable
TypeError: 'NoneType' object is not callable
```

(able to get the `loss`, but report the error). 

------
By the way, i am able to run the test example of https://github.com/alpa-projects/alpa/tree/main/examples/mnist without any error, and I wonder if this error is only me. Thanks! Or it seems the states for the NN will eventually deleted and does not support the parallelism of the common python function.

**Comment by merrymercy** [comment]
All of them are fixed in https://github.com/alpa-projects/alpa

**Comment by JiahaoYao** [comment]
thanks！
