### ISSUE TITLE
Unable to run test_torch_zhen.py with slightly increased input size

### ISSUE THREAD

**Issue by crazyboycjr** [alpa-projects/alpa#523]
**Please describe the bug**
This issue only appears when I increase the input size of the model in `test_torch_zhen.py`.

**Please describe the expected behavior**
Program run to completion without any error.

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker):
- Python version: 3.8.13
- CUDA version: 11.4
- NCCL version: 2.12.7
- cupy version: 10.5.0
- GPU model and memory: p3.16xlarge
- Alpa version: d9a21eb6d07a0df60ac20db2dc56fc9710ebe4b1
- TensorFlow version: 4c882b008156c5b3f00e5566c30812c8c176b1a0
- JAX version: 0.3.5

**To Reproduce**
1. Enable torch support following the step in install.rst
2. slightly increase the input size in `tests/test_torch_zhen.py`, e.g., in `test_zhen_homogeneous()`, B=128, F=642, D=160, OUTPUT_PER_ENSEMBLE=24.
3. run `python3 tests/test_torch_zhen.py` on two p3.16xlarge nodes

**Screenshots**
The screenshot shows when the program got stuck. The left two panes are node 1, and the right two panes are node 2.
![image](https://user-images.githubusercontent.com/9761046/174207313-239f0d75-e89b-4076-9075-0d1e7c7d2894.png)

**Code snippet to reproduce the problem**
tests/test_torch_zhen.py

**Additional information**
If running with `RAY_IGNORE_UNHANDLED_ERRORS=1`, the program will stuck forever, with all CPUs running at 100% (mostly in kernel threads).

I see there is a NCCL_ERROR_UNHANDLED_ERROR, so I tried nccl-tests with various size, and it seems to work fine.

Log:
```
...
/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py:1866: UserWarning: Explicitly requested dtype <class 'numpy.float64'> requested in asarray is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  lax_internal._check_user_dtype_supported(dtype, "asarray")
/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/jax/_src/numpy/lax_numpy.py:1866: UserWarning: Explicitly requested dtype <class 'numpy.float64'> requested in asarray is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  lax_internal._check_user_dtype_supported(dtype, "asarray")
-------------------- Automatic stage clustering --------------------
submesh_choices: ((1, 1), (1, 2), (1, 4), (1, 8), (2, 8))
- Profiling for submesh 4 (2, 8):
- Generate all stage infos (Jaxpr -> HLO)
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:01<00:00,  1.26it/s]
- Compile all stages
  0%|                                                                                                     | 0/1 [00:00<?, ?it/s](CompileWorker pid=127849) 2022-06-17 00:46:48.319036: F external/org_tensorflow/tensorflow/compiler/xla/service/spmd/auto_sharding.cc:1453] Check failed: strategies->is_tuple || !strategies->leaf_vector.empty() %slice.2054 = f32[1,1,24]{2,1,0} slice(f32[64,1,24]{2,1,0} %reduce.492), slice={[0:1], [0:1], [0:24]} does not have any valid strategies.
(CompileWorker pid=127849) *** SIGABRT received at time=1655426808 on cpu 24 ***
(CompileWorker pid=127849) PC: @     0x7f2c4939ce87  (unknown)  raise
(CompileWorker pid=127849)     @     0x7f2c49761980  (unknown)  (unknown)
(CompileWorker pid=127849)     @     0x7f07f1b28a8d      10384  xla::spmd::BuildStrategyAndCost()
(CompileWorker pid=127849)     @     0x7f07f1b2d3ff       2272  xla::spmd::AutoSharding::Run()
(CompileWorker pid=127849)     @     0x7f07f52d1d2d        880  xla::HloPassPipeline::RunPassesInternal<>()
(CompileWorker pid=127849)     @     0x7f07f52d29b2        464  xla::HloPassPipeline::Run()
(CompileWorker pid=127849)     @     0x7f07f1afbcd6       3296  xla::spmd::RunAutoShardingPass()
(CompileWorker pid=127849)     @     0x7f07f1a47052        176  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
(CompileWorker pid=127849)     @     0x7f07f17ed739        800  pybind11::cpp_function::dispatcher()
(CompileWorker pid=127849)     @     0x5640f3d9b00e  (unknown)  cfunction_call_varargs
(CompileWorker pid=127849)     @     0x5640f3fb1660  (unknown)  (unknown)
(CompileWorker pid=127849) [2022-06-17 00:46:48,385 E 127849 127849] logging.cc:325: *** SIGABRT received at time=1655426808 on cpu 24 ***
(CompileWorker pid=127849) [2022-06-17 00:46:48,385 E 127849 127849] logging.cc:325: PC: @     0x7f2c4939ce87  (unknown)  raise
(CompileWorker pid=127849) [2022-06-17 00:46:48,387 E 127849 127849] logging.cc:325:     @     0x7f2c49761980  (unknown)  (unknown)
(CompileWorker pid=127849) [2022-06-17 00:46:48,387 E 127849 127849] logging.cc:325:     @     0x7f07f1b28a8d      10384  xla::spmd::BuildStrategyAndCost()
(CompileWorker pid=127849) [2022-06-17 00:46:48,387 E 127849 127849] logging.cc:325:     @     0x7f07f1b2d3ff       2272  xla::spmd::AutoSharding::Run()
(CompileWorker pid=127849) [2022-06-17 00:46:48,387 E 127849 127849] logging.cc:325:     @     0x7f07f52d1d2d        880  xla::HloPassPipeline::RunPassesInternal<>()
(CompileWorker pid=127849) [2022-06-17 00:46:48,387 E 127849 127849] logging.cc:325:     @     0x7f07f52d29b2        464  xla::HloPassPipeline::Run()
(CompileWorker pid=127849) [2022-06-17 00:46:48,387 E 127849 127849] logging.cc:325:     @     0x7f07f1afbcd6       3296  xla::spmd::RunAutoShardingPass()
(CompileWorker pid=127849) [2022-06-17 00:46:48,387 E 127849 127849] logging.cc:325:     @     0x7f07f1a47052        176  pybind11::cpp_function::initialize<>()::{lambda()#3}::_FUN()
(CompileWorker pid=127849) [2022-06-17 00:46:48,387 E 127849 127849] logging.cc:325:     @     0x7f07f17ed739        800  pybind11::cpp_function::dispatcher()
(CompileWorker pid=127849) [2022-06-17 00:46:48,387 E 127849 127849] logging.cc:325:     @     0x5640f3d9b00e  (unknown)  cfunction_call_varargs
(CompileWorker pid=127849) [2022-06-17 00:46:48,390 E 127849 127849] logging.cc:325:     @     0x5640f3fb1660  (unknown)  (unknown)
(CompileWorker pid=127849) Fatal Python error: Aborted
(CompileWorker pid=127849)
(CompileWorker pid=127849) Stack (most recent call first):
(CompileWorker pid=127849)   File "/home/cjr/alpa-torch-software/alpa/alpa/shard_parallel/auto_sharding.py", line 345 in run_auto_sharding_pass
(CompileWorker pid=127849)   File "/home/cjr/alpa-torch-software/alpa/alpa/pipeline_parallel/stage_profiling.py", line 166 in compile_stage_for_profiling
(CompileWorker pid=127849)   File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 462 in _resume_span
(CompileWorker pid=127849)   File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/_private/function_manager.py", line 701 in actor_method_executor
(CompileWorker pid=127849)   File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/worker.py", line 449 in main_loop
(CompileWorker pid=127849)   File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/workers/default_worker.py", line 235 in <module>
2022-06-17 00:46:57,424 WARNING worker.py:1382 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffffd0f840f77ea11d3c4b9111b712000000 Worker ID: acbe209655ea183558e0f47cb0e6d8213820b7e5373fd208aa367716 Node ID: 816cc3dd4541afaf2685fc5140c359bd5889c5592cebaf6138720184 Worker IP address: 172.31.0.219 Worker port: 10573 Worker PID: 127849
WARNING:alpa.pipeline_parallel.stage_profiling:A Compile worker died unexpectedly: The actor died unexpectedly before finishing this task.
        class_name: CompileWorker
        actor_id: d0f840f77ea11d3c4b9111b712000000
        pid: 127849
        namespace: c1b5e87c-79a1-4d79-a974-55b29efa401c
        ip: 172.31.0.219
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR_EXIT
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:11<00:00, 11.79s/it]
- Profile all stages
0it [00:00, ?it/s]
Profiling for submesh 4 (2, 8) takes 13.626534223556519 seconds
Profiled costs are: [[[inf]
  [inf]]

 [[inf]
  [inf]]]
Profiled max_n_succ_stages are: [[[-1]
  [-1]]

 [[-1]
  [-1]]]
--------------------------------------------------
- Profiling for submesh 3 (1, 8):
- Generate all stage infos (Jaxpr -> HLO)
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.56s/it]
- Compile all stages
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:10<00:00,  3.35s/it]
- Profile all stages
cost[0, 0, 0]=0.009, max_n_succ_stage=104, Mem: avail=13.932GB, peak=0.540GB, intermediate=0.126GB, init=0.101GB, as_config=((1, 8), {})
cost[0, 1, 0]=0.023, max_n_succ_stage=52, Mem: avail=13.664GB, peak=0.567GB, intermediate=0.242GB, init=0.131GB, as_config=((1, 8), {})
cost[1, 1, 0]=0.018, max_n_succ_stage=115, Mem: avail=13.932GB, peak=0.156GB, intermediate=0.118GB, init=0.030GB, as_config=((1, 8), {})
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [01:01<00:00, 20.34s/it]
Profiling for submesh 3 (1, 8) takes 74.59861373901367 seconds
Profiled costs are: [[[0.00949785]
  [0.02315802]]

 [[       inf]
  [0.01776624]]]
Profiled max_n_succ_stages are: [[[104]
  [ 52]]

 [[ -1]
  [115]]]
--------------------------------------------------
- Profiling for submesh 2 (1, 4):
- Generate all stage infos (Jaxpr -> HLO)
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.60s/it]
- Compile all stages
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:10<00:00,  3.40s/it]
- Profile all stages
cost[0, 0, 0]=0.015, max_n_succ_stage=92, Mem: avail=13.932GB, peak=0.763GB, intermediate=0.138GB, init=0.199GB, as_config=((1, 4), {})
cost[1, 1, 0]=0.020, max_n_succ_stage=73, Mem: avail=13.664GB, peak=0.254GB, intermediate=0.179GB, init=0.048GB, as_config=((1, 4), {})
cost[0, 1, 0]=0.029, max_n_succ_stage=51, Mem: avail=13.932GB, peak=0.893GB, intermediate=0.243GB, init=0.248GB, as_config=((1, 4), {})
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:50<00:00, 16.97s/it]
Profiling for submesh 2 (1, 4) takes 64.77020406723022 seconds
Profiled costs are: [[[0.01470545]
  [0.02861537]]

 [[       inf]
  [0.01999275]]]
Profiled max_n_succ_stages are: [[[92]
  [51]]

 [[-1]
  [73]]]
--------------------------------------------------
- Profiling for submesh 1 (1, 2):
- Generate all stage infos (Jaxpr -> HLO)
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.68s/it]
- Compile all stages
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:10<00:00,  3.40s/it]
- Profile all stages
cost[0, 0, 0]=0.023, max_n_succ_stage=106, Mem: avail=13.932GB, peak=1.331GB, intermediate=0.114GB, init=0.396GB, as_config=((1, 2), {})
cost[1, 1, 0]=0.028, max_n_succ_stage=43, Mem: avail=13.932GB, peak=0.444GB, intermediate=0.303GB, init=0.085GB, as_config=((1, 2), {})
cost[0, 1, 0]=0.038, max_n_succ_stage=27, Mem: avail=13.932GB, peak=1.745GB, intermediate=0.416GB, init=0.481GB, as_config=((1, 2), {})
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:49<00:00, 16.40s/it]
Profiling for submesh 1 (1, 2) takes 63.227320432662964 seconds
Profiled costs are: [[[0.022597  ]
  [0.03761835]]

 [[       inf]
  [0.0280806 ]]]
Profiled max_n_succ_stages are: [[[106]
  [ 27]]

 [[ -1]
  [ 43]]]
--------------------------------------------------
- Profiling for submesh 0 (1, 1):
- Generate all stage infos (Jaxpr -> HLO)
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:03<00:00,  1.57s/it]
- Compile all stages
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:02<00:00,  1.41it/s]
- Profile all stages
cost[1, 1, 0]=0.037, max_n_succ_stage=22, Mem: avail=13.932GB, peak=0.836GB, intermediate=0.551GB, init=0.158GB, as_config=((1, 1), {})
cost[0, 0, 0]=0.042, max_n_succ_stage=49, Mem: avail=13.932GB, peak=2.553GB, intermediate=0.212GB, init=0.789GB, as_config=((1, 1), {})
cost[0, 1, 0]=0.057, max_n_succ_stage=11, Mem: avail=13.932GB, peak=3.361GB, intermediate=0.763GB, init=0.947GB, as_config=((1, 1), {})
100%|█████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:28<00:00,  9.64s/it]
Profiling for submesh 0 (1, 1) takes 34.60442018508911 seconds
Profiled costs are: [[[0.0415114 ]
  [0.05681266]]

 [[       inf]
  [0.0369432 ]]]
Profiled max_n_succ_stages are: [[[49]
  [11]]

 [[-1]
  [22]]]
--------------------------------------------------
Compute cost saved to: compute-cost-2022-06-17-00-50-54.npy
----------------------------------------------------------------------
Result forward_stage_layer_ids: [[0], [1]]
Result meshes: [(1, 8), (1, 8)]
Result logical_mesh_shapes: [(1, 8), (1, 8)]
Result autosharding_option_dicts: [{}, {}]
2022-06-17 00:53:49,171 ERROR worker.py:92 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): ray::MeshHostWorker.run_executable() (pid=95410, ip=172.31.1.220, repr=<alpa.device_mesh.MeshHostWorker object at 0x7fd30d092430>)
  File "/home/cjr/alpa-torch-software/alpa/alpa/device_mesh.py", line 266, in run_executable
    self.executables[uuid].execute_on_worker(*args, **kwargs)
  File "/home/cjr/alpa-torch-software/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 482, in execute_on_worker
    self.worker.run_resharding_recv_task(
  File "/home/cjr/alpa-torch-software/alpa/alpa/device_mesh.py", line 524, in run_resharding_recv_task
    self.recv_tile(buf_uuid, recv_spec.device_id,
  File "/home/cjr/alpa-torch-software/alpa/alpa/device_mesh.py", line 448, in recv_tile
    col.recv_multigpu(to_recv[ind],
  File "/home/cjr/alpa-torch-software/alpa/alpa/collective/collective.py", line 668, in recv_multigpu
    g.recv([tensor], opts)
  File "/home/cjr/alpa-torch-software/alpa/alpa/collective/collective_group/nccl_collective_group.py", line 497, in recv
    self._point2point(tensors, p2p_fn, recv_options.src_rank,
  File "/home/cjr/alpa-torch-software/alpa/alpa/collective/collective_group/nccl_collective_group.py", line 808, in _point2point
    p2p_fn(t, comms[i], streams[i], peer_p2p_rank)
  File "/home/cjr/alpa-torch-software/alpa/alpa/collective/collective_group/nccl_collective_group.py", line 491, in p2p_fn
    comm.recv(
  File "cupy_backends/cuda/libs/nccl.pyx", line 477, in cupy_backends.cuda.libs.nccl.NcclCommunicator.recv
  File "cupy_backends/cuda/libs/nccl.pyx", line 129, in cupy_backends.cuda.libs.nccl.check_status
cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_SYSTEM_ERROR: unhandled system error
^CTraceback (most recent call last):
  File "tests/test_torch_zhen.py", line 538, in <module>
    runner.run(suite())
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "tests/test_torch_zhen.py", line 489, in test_zhen_homogeneous
    train_torch_module(pt_module_gen, weight_init_func, dataloader,
  File "/home/cjr/alpa-torch-software/alpa/alpa/torch/trainer.py", line 133, in train_torch_module
    params, bufs, optim_state, _ = iter_func(params, bufs, optim_state,
  File "/home/cjr/alpa-torch-software/alpa/alpa/torch/trainer.py", line 115, in iter_func
    params, bufs, optim_state, loss_value = train_func(
  File "/home/cjr/alpa-torch-software/alpa/alpa/api.py", line 103, in __call__
    out = executable.launch_on_driver(*args_flat)
  File "/home/cjr/alpa-torch-software/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 230, in launch_on_driver
    self._check_alive()
  File "/home/cjr/alpa-torch-software/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 360, in _check_alive
    ray.get(rets)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/worker.py", line 1803, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/worker.py", line 362, in get_objects
    data_metadata_pairs = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 1198, in ray._raylet.CoreWorker.get_objects
  File "python/ray/_raylet.pyx", line 167, in ray._raylet.check_status
KeyboardInterrupt
Exception ignored in: <function PipeshardDriverExecutable.__del__ at 0x7f8ea677eaf0>
Traceback (most recent call last):
  File "/home/cjr/alpa-torch-software/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 366, in __del__
    worker.delete_executable.remote(uuid)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/actor.py", line 122, in remote
    return self._remote(args, kwargs)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/util/tracing/tracing_helper.py", line 421, in _start_span
    return method(self, args, kwargs, *_args, **_kwargs)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/actor.py", line 168, in _remote
    return invocation(args, kwargs)
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/actor.py", line 155, in invocation
    return actor._actor_method_call(
  File "/home/cjr/miniconda3/envs/alpa-torch/lib/python3.8/site-packages/ray/actor.py", line 1168, in _actor_method_call
    object_refs = worker.core_worker.submit_actor_task(
AttributeError: 'Worker' object has no attribute 'core_worker'

python3 tests/test_torch_zhen.py  55.31s user 11.82s system 11% cpu 9:55.45 total
```

**Comment by crazyboycjr** [comment]
Thanks for the advice! I tried to round up all the numbers to 32, but it's still getting the same results.

**Comment by crazyboycjr** [comment]
Thanks for the advice! I tried to round up all the numbers to 32, but it's still getting the same results.

**Comment by zhuohan123** [comment]
Do you still get this error? Can you post the new complete error message?
`Check failed: strategies->is_tuple || !strategies->leaf_vector.empty() %slice.2054 = f32[1,1,24]{2,1,0} slice(f32[64,1,24]{2,1,0} %reduce.492), slice={[0:1], [0:1], [0:24]} does not have any valid strategies. `

**Comment by crazyboycjr** [comment]
```2022-06-17 04:12:31.417976: F external/org_tensorflow/tensorflow/compiler/xla/service/spmd/auto_sharding.cc:1453] Check failed: strategies->is_tuple || !strategies->leaf_vector.empty() %slice.2054 = f32[1,1,32]{2,1,0} slice(f32[64,1,32]{2,1,0} %reduce.492), slice={[0:1], [0:1], [0:32]} does not have any valid strategies.```

If the input size is smaller (e.g., B=4, F=642, D=160), the program can successfully run to completion.

**Comment by merrymercy** [comment]
I fixed multiple bugs in the ZHEN model implementation (https://github.com/alpa-projects/alpa/pull/530) and alpa's batch dim analysis (https://github.com/alpa-projects/tensorflow-alpa/pull/118).
Now I can successfully run the case you mentioned (test_zhen_homogeneous(), B=128, F=642, D=160, OUTPUT_PER_ENSEMBLE=24.)

**Comment by crazyboycjr** [comment]
Fantastic! Thank you so much!

**Comment by merrymercy** [comment]
Yes. This is expected.

**Comment by crazyboycjr** [comment]
Great, thanks! @merrymercy

Both the two issues are solved now. The first issue was solved by code according to [this reply](https://github.com/alpa-projects/alpa/issues/523#issuecomment-1159991406). The second issue of hanging NCCL was caused by creating too many connections. A temporary workaround is to increase the ulimit of nofile to 65536.

I'm going to close the issue.

**Comment by crazyboycjr** [comment]
Great, thanks! @merrymercy 

Both the two issues are solved now. The first issue was solved by code according to [this comment](https://github.com/alpa-projects/alpa/issues/523#issuecomment-1159991406). The second issue of hanging NCCL was caused by creating too many connections. A temporary workaround is to increase the ulimit of nofile to 65536.

I'm going to close the issue.
