### ISSUE TITLE
Launch Web Generate Example Failed

### ISSUE THREAD

**Issue by wgimperial** [alpa-projects/alpa#566]
Run command: python3 interactive_hosted.py --model alpa/opt-125m --port 10001 --path /home/alpa_for_metaopt/alpa_model/
Launch web generate example test failed.

exception :
Traceback (most recent call last):
  File "interactive_hosted.py", line 64, in batching_loop
    item = target_queue.get(timeout=timeout / 1000)
  File "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/site-packages/examples/opt_serving/dataset/token_block_dataset.py", line 109, in _build_slice_indices
    from examples.opt_serving.dataset.token_block_utils_fast import (
ModuleNotFoundError: No module named 'examples.opt_serving.dataset.token_block_utils_fast'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "interactive_hosted.py", line 104, in batching_loop
    generations = generator.generate(**request_object)
  File "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/site-packages/examples/opt_serving/generator.py", line 378, in generate
    dataset=self.build_dataset_for_inference(tokens, lengths),
  File "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/site-packages/examples/opt_serving/generator.py", line 536, in build_dataset_for_inference
    dataset = TokenBlockDataset(src_tokens,
  File "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/site-packages/examples/opt_serving/dataset/token_block_dataset.py", line 72, in __init__
    _sizes, block_to_dataset_index, slice_indices = self._build_slice_indices(
  File "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/site-packages/examples/opt_serving/dataset/token_block_dataset.py", line 114, in _build_slice_indices
    raise ImportError(
ImportError: Please build Cython components with: `pip install --editable .` or `python setup.py build_ext --inplace`

**Comment by zhisbug** [comment]
@wgimperial did you follow the guide to compile the cython files? @wgimperial

**Comment by wgimperial** [comment]
> @wgimperial did you follow the guide to compile the cython files? @wgimperial

Step 1: uninstall older version Cython
Step 2: git clone https://github.com/cython/cython.git
Step 3: cd cython 
Step 4: pip install --editable .
After install, error still exists

**Comment by wgimperial** [comment]
> > > @wgimperial did you follow the guide to compile the cython files? @wgimperial
> > 
> > 
> > Step 1: uninstall older version Cython
> > Step 2: git clone https://github.com/cython/cython.git
> > Step 3: cd cython
> > Step 4: pip install --editable .
> > After install, error still exists
> 
> I meant you need to follow step 3 of the requirement section in the tutorial to compile several files under dataset folder; (instead of compiling cython library from source)

Step 3 already done,  token_block_utils_fast.cpython-38-x86_64-linux-gnu.so exits in dataset folder,  but still exits error

**Comment by zhisbug** [comment]
@wgimperial I have no idea why you cannot import if you have built successfully.

**Comment by zhisbug** [comment]
@wgimperial I tried to invite you to slack but it shows the following error: 
<img width="598" alt="image" src="https://user-images.githubusercontent.com/1654062/176940539-9b2d8f67-0951-48e5-ac00-bd2fffd450c4.png">

**Comment by wgimperial** [comment]
> @wgimperial I have no idea why you cannot import if you have built successfully. Could you just try to import `token_block_utils_fast` and try to debug the import error?

Thanks for your relpay! Now the web function is ok. We did this:
According to the error stack, we modified the "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/site-packages/examples/opt_serving/dataset/token_block_dataset.py" and "/root/anaconda3/envs/alpa-cuda113/lib/python3.8/site-packages/examples/opt_serving/dataset/data_utils.py"
"from examples.opt_serving.dataset.data_utils_fast import " to "from dataset.data_utils_fast import ".
And we found master branch of alpa these two files has same problem?
