### ISSUE TITLE
Install alpa in docker Failed

### ISSUE THREAD

**Issue by wgimperial** [alpa-projects/alpa#579]
**Please describe the bug**

We install alpa in docker ,base image from: nvidia/cuda:11.3.0-cudnn8-devel-ubuntu20.04.
Follow the alpa install instructions, run commonds in docker：
1、apt install coinor-cbc
2、pip3 install --upgrade pip
3、pip3 install cupy-cuda113
4、python3 -c "from cupy.cuda import nccl"    --> OK
5、pip3 install alpa
6、pip3 install jaxlib-0.3.5+cuda113.cudnn820-cp38-none-manylinux2010_x86_64.whl

Ray start is ok，continue install：
a、pip3 install transformers flask cython omegaconf -i https://pypi.douban.com/simple
b、pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113 -i https://pypi.douban.com/simple

then run opt-125m follow the demo，error：
cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_SYSTEM_ERROR: unhandled system error

detail info：
Load model alpa/opt-125m ... (This can take several minutes for very large models)
Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    model = get_model(model_name="alpa/opt-125m",
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/examples/opt_serving/model/wrapper.py", line 305, in get_model
    executable, params_aval = get_pipeshard_executable(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/examples/opt_serving/model/opt_model.py", line 706, in get_pipeshard_executable
    executable = inference_step_with_cache.get_executable(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/api.py", line 110, in get_executable
    executable, _, _, _ = self._decode_args_and_get_executable(*args)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/api.py", line 174, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/jax/linear_util.py", line 272, in memoized_fun
    ans = call(fun, *args)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/api.py", line 201, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/parallel_method.py", line 219, in compile_executable
    return compile_pipeshard_executable(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/compile_executable.py", line 76, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/compile_executable.py", line 217, in compile_pipeshard_executable_internal
    pipeshard_config = PipelineInstEmitter(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 387, in compile
    self._compile_resharding_tasks()
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 326, in _compile_resharding_tasks
    var] = SymbolicReshardingTask(spec, cg, src_mesh,
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 370, in __init__
    self._compile()
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 449, in _compile
    self.put_all_tasks()
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 478, in put_all_tasks
    ray.get(task_dones)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/ray/worker.py", line 1831, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(NcclError): ray::MeshHostWorker.put_resharding_allgather_task() (pid=5657, ip=172.17.0.2, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f08fdb63880>)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/device_mesh.py", line 480, in put_resharding_allgather_task
    worker_nccl_util.init_local_comm(list(device_ids)))
  File "cupy_backends/cuda/libs/nccl.pyx", line 338, in cupy_backends.cuda.libs.nccl.NcclCommunicator.initAll
  File "cupy_backends/cuda/libs/nccl.pyx", line 360, in cupy_backends.cuda.libs.nccl.NcclCommunicator._initAll
  File "cupy_backends/cuda/libs/nccl.pyx", line 129, in cupy_backends.cuda.libs.nccl.check_status
cupy_backends.cuda.libs.nccl.NcclError: NCCL_ERROR_SYSTEM_ERROR: unhandled system error

The same operation is ok without install in docker, any idea?

**Comment by zhisbug** [comment]
@wgimperial  Hi, we currently do not provide official docker support, though our CI and wheel building all actually run in docker. 

If you want to run the distributed training or inference in docker, we recommend you to refer to these dockerfiles we used to build CI/CD: https://github.com/alpa-projects/alpa/blob/main/docker/build_jaxlib.Dockerfile

It should be very straightforward to adapt them to run Alpa training/inference in docker.

You're also welcome to contribute the dockerfile you successfully adapt afterward to our repo by submitting a PR

**Comment by wgimperial** [comment]
I install alpa in docker ,and run opt demo (follow https://alpa-projects.github.io/tutorials/opt_serving.html#launch-a-web-server-to-serve-the-opt-models) on different machines,which are  4 gpus and  6 gpus。Success in 4 gpus machine，but failed in 6 gpus，error info：

Traceback (most recent call last):
  File "demo.py", line 10, in <module>
    model = get_model(model_name="alpa/opt-125m",
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/examples/opt_serving/model/wrapper.py", line 237, in get_model
    executable, params_aval = get_pipeshard_executable(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/examples/opt_serving/model/opt_model.py", line 708, in get_pipeshard_executable
    executable = inference_step_with_cache.get_executable(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/api.py", line 110, in get_executable
    executable, _, _, _ = self._decode_args_and_get_executable(*args)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/api.py", line 174, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/jax/linear_util.py", line 272, in memoized_fun
    ans = call(fun, *args)
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/api.py", line 201, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/parallel_method.py", line 225, in compile_executable
    return compile_pipeshard_executable(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/compile_executable.py", line 69, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/compile_executable.py", line 210, in compile_pipeshard_executable_internal
    pipeshard_config = PipelineInstEmitter(
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 415, in compile
    outs_handler = self._get_outs_handler(mesh_output_indices,
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 964, in _get_outs_handler
    indices_list.append(pxla.spec_to_indices(aval.shape, spec))
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 288, in spec_to_indices
    return tuple(spec.indices(shape).flat)  # type: ignore
  File "/opt/conda/envs/alpa/lib/python3.8/site-packages/jax/interpreters/pxla.py", line 227, in sharding_spec_indices
    assert not ragged, (axis_size, total_chunks, dim)
AssertionError: (50272, 3, 2)

By the way ,Same with the two machine's system(Ubuntu 20.04) and nvidia driver ,what went wrong？@zhisbug

**Comment by zhisbug** [comment]
@wgimperial This is a runtime error. 

In the OPT serving example, we hand-write a parallel strategy with num_stage = 2. So each stage will be shared across 3 GPUs (since you have 6 in total). But in OPT model computation, there is no dimension that can be divided by 3, hence the error.

**Comment by zhisbug** [comment]
@wgimperial If possible, do you mind contributing the docker image you adapted to run Alpa to Alpa upstream? Thank you!

**Comment by wgimperial** [comment]
ok, i'll submitting a PR later.

**Comment by merrymercy** [comment]
@wgimperial The assertion error `AssertionError: (50272, 3, 2)` is fixed by https://github.com/alpa-projects/tensorflow-alpa/pull/122). If you pip install the latest jaxlib again, you should be able to run the opt on a 6-gpu node

**Comment by wgimperial** [comment]
Thx，and is it possible to provide a opt-66b alpa-compatible weights?
