### ISSUE TITLE
Error on testing alpa installation

### ISSUE THREAD

**Issue by johncedc** [alpa-projects/alpa#582]
Hi All, I am trying to setup the OPT-175 model using alpa and ray. Followed all instructions https://alpa-projects.github.io/install.html#prerequisites. Have been able to convert the weights as well. However, I get the following error when loading the model: KeyError: Actor(MeshHostWorker, 926198553ac61b167bbd508003000000). When I run the "python3 tests/test_install.py" script to test the alpa installation, I get the same error. Can someone please help.

**Comment by zhisbug** [comment]
@johncedc Please follow issue template and provide detailed traceback and screenshot.

**Comment by johncedc** [comment]
> @johncedc Please follow issue template and provide detailed traceback and screenshot.

@zhisbug Please find below the detailed traceback

Environment used: 
A100 40 GB GPU, 
CUDA: 11.3, 
Cudnn: 8.2, 
Driver Version: 470.57.02
Python: 3.8
Installed alpa using Python wheel following instructions "https://alpa-projects.github.io/install.html"
 
!python3 tests/test_install.py
.E
======================================================================
ERROR: test_2_pipeline_parallel (__main__.InstallationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/test_install.py", line 122, in <module>
    runner.run(suite())
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/unittest/runner.py", line 176, in run
    test(result)
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/unittest/suite.py", line 122, in run
    test(result)
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/unittest/case.py", line 736, in __call__
    return self.run(*args, **kwds)
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/unittest/case.py", line 676, in run
    self._callTestMethod(testMethod)
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/unittest/case.py", line 633, in _callTestMethod
    method()
  File "tests/test_install.py", line 107, in test_2_pipeline_parallel
    actual_state = p_train_step(state, batch)
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/api.py", line 104, in __call__
    self._decode_args_and_get_executable(*args))
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/api.py", line 174, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/jax/linear_util.py", line 272, in memoized_fun
    ans = call(fun, *args)
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/api.py", line 201, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/parallel_method.py", line 219, in compile_executable
    return compile_pipeshard_executable(
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/compile_executable.py", line 76, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/compile_executable.py", line 217, in compile_pipeshard_executable_internal
    pipeshard_config = PipelineInstEmitter(
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 387, in compile
    self._compile_resharding_tasks()
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 326, in _compile_resharding_tasks
    var] = SymbolicReshardingTask(spec, cg, src_mesh,
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 370, in __init__
    self._compile()
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 444, in _compile
    self._compile_send_recv_tasks()
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 544, in _compile_send_recv_tasks
    self._sender_tasks[sender_worker].append(
jax._src.traceback_util.UnfilteredStackTrace: KeyError: Actor(MeshHostWorker, cb7f1d88b0c8c715fa3c5ab801000000)

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tests/test_install.py", line 107, in test_2_pipeline_parallel
    actual_state = p_train_step(state, batch)
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/api.py", line 104, in __call__
    self._decode_args_and_get_executable(*args))
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/api.py", line 174, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/api.py", line 201, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/parallel_method.py", line 219, in compile_executable
    return compile_pipeshard_executable(
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/compile_executable.py", line 76, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/compile_executable.py", line 217, in compile_pipeshard_executable_internal
    pipeshard_config = PipelineInstEmitter(
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 387, in compile
    self._compile_resharding_tasks()
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 326, in _compile_resharding_tasks
    var] = SymbolicReshardingTask(spec, cg, src_mesh,
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 370, in __init__
    self._compile()
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 444, in _compile
    self._compile_send_recv_tasks()
  File "/home/user1/anaconda3/envs/env1/lib/python3.8/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 544, in _compile_send_recv_tasks
    self._sender_tasks[sender_worker].append(
KeyError: Actor(MeshHostWorker, cb7f1d88b0c8c715fa3c5ab801000000)

----------------------------------------------------------------------
Ran 2 tests in 8.687s

FAILED (errors=1)

Similar error, when loading model:

![image](https://user-images.githubusercontent.com/108618785/177094327-25151f23-96c2-433e-bfc4-95867843cc2b.png)
![image](https://user-images.githubusercontent.com/108618785/177094514-7797399b-53ed-4ab4-acb6-124be28074cf.png)
![image](https://user-images.githubusercontent.com/108618785/177094593-d8aafc04-7640-4b43-87f0-19fd662fd2a7.png)
![image](https://user-images.githubusercontent.com/108618785/177094670-4a3884c2-5033-48b1-b90d-496d36703096.png)
![image](https://user-images.githubusercontent.com/108618785/177094745-8d0ae3b4-6560-4bed-b5ea-fa023f7c0fdc.png)
![image](https://user-images.githubusercontent.com/108618785/177094796-20c8332b-3f46-4cdd-8c6c-f55720ac1c4a.png)

**Comment by zhisbug** [comment]
@johncedc Could you run cupy test files [under this folder ](https://github.com/alpa-projects/alpa/tree/main/benchmark/cupy)and see if they can run successfully. Otherwise, You want to follow #496 and #570 (see discussion here: https://github.com/alpa-projects/alpa/issues/570#issuecomment-1174067779) to upgrade your NVIDIA driver?

We'll add a section in the installation doc to describe this issue (which seems common to many users)

**Comment by zhisbug** [comment]
@johncedc Could you also share your cluster spec -- how many node you have? how many GPUs on each node?

**Comment by JiahaoYao** [comment]
Hi @johncedc , i wonder whether you have fix your issue, i was using the following script to install alpa 

```python
conda create -n alpa python==3.9 
conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch
pip install ray[default] torch torchvision tensorboardX boto3 matplotlib clu einops
ray install-nightly
pip install boto3
sudo rm -rf /var/lib/apt/lists/lock
sudo rm -rf /var/cache/apt/archives/lock
sudo rm -rf /var/lib/dpkg/lock*
sudo dpkg --configure -a
sudo apt update
sudo apt install coinor-cbc -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
sudo apt-get update
sudo apt-get install --only-upgrade libstdc++6 -y

sudo rm -rf /usr/local/cuda
sudo ln -s /usr/local/cuda-11.3 /usr/local/cuda
pip install pip --upgrade
pip install ipdb
pip install cupy-cuda113
python -m cupyx.tools.install_library --cuda 11.3 --library nccl
python -c "from cupy.cuda import nccl"
pip install jax==0.3.5
pip install flax==0.4.1
pip install https://github.com/alpa-projects/alpa/releases/download/v0.1.4/jaxlib-0.3.5%2Bcuda113.cudnn820-cp39-none-manylinux2010_x86_64.whl
pip install alpa
pip uninstall tensorflow -y 
pip install tensorflow --upgrade
git clone https://github.com/alpa-projects/alpa
```

**Comment by JiahaoYao** [comment]
more info: 

using the aws ami
<div class="GCO2-UEDFAB" style="margin-bottom: 10px; border-bottom: 1px solid rgb(85, 85, 85); color: rgb(255, 255, 255); font-family: &quot;Helvetica Neue&quot;, Roboto, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="GCO2-UEDEAB" style="font-weight: bold; border-bottom: 1px solid rgb(51, 51, 51); padding-bottom: 8px;">Deep Learning AMI (Ubuntu 18.04) Version 63.0 (ami-0bd0060cbc407b47e)</div></div><div class="GCO2-UEDAAB" style="color: rgb(255, 255, 255); font-family: &quot;Helvetica Neue&quot;, Roboto, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div id="gwt-debug-tabularDetails">

  |  
-- | --
DescriptionMXNet-1.9, TensorFlow-2.7, PyTorch-1.11, Neuron, & others. NVIDIA CUDA, cuDNN, NCCL, Intel MKL-DNN, Docker, NVIDIA-Docker & EFA support. For fully managed experience, check: https://aws.amazon.com/sagemaker
Statusavailable
PlatformUbuntu
Image Size140GB
VisibilityPublic
Owner898082745236

</div></div>

**Comment by merrymercy** [comment]
closed due to inactivity
