### ISSUE TITLE
conver 66B model shards into one single fail

### ISSUE THREAD

**Issue by incrideble** [alpa-projects/alpa#601]
use step_2_consolidate_992_shards_to_singleton.py script to merge 66B model shards fail ,fail info:
Traceback (most recent call last):
  File "metaseq/scripts/consolidate_fsdp_shards.py", line 13, in <module>
    fire.Fire(consolidate_fsdp_shards)
  File "/root/anaconda3/envs/metaseq_train/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/root/anaconda3/envs/metaseq_train/lib/python3.8/site-packages/fire/core.py", line 466, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/root/anaconda3/envs/metaseq_train/lib/python3.8/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/alpa_for_metaopt/metaseq/metaseq/distributed/stitch_fsdp_ckpt.py", line 72, in consolidate_fsdp_shards
    metadata.append(ckpt["shard_metadata"])
KeyError: 'shard_metadata'

**Comment by apoorvumang** [comment]
hey @incrideble , how were you able to achieve these? I am having the same issue. Any help is appreciated 😃

**Comment by zhanghaoie** [comment]
I have the same issue, have you solved this problem?
