### ISSUE TITLE
test_install failed after fresh install

### ISSUE THREAD

**Issue by JACKHAHA363** [alpa-projects/alpa#635]
**Please describe the bug**
Failed `alpa.test_install` after fresh installation (tried both pre-built wheels as well as build from source)
```
(tester-xS3fZVNL-py3.9) root@9b431273952e:/workspace/alpa/examples/opt_serving# python -m alpa.test_install
======================================================================
FAIL: test_1_shard_parallel (__main__.InstallationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/alpa/alpa/test_install.py", line 30, in test_1_shard_parallel
    assert_allclose(expected_output, actual_output)
  File "/workspace/alpa/alpa/testing.py", line 37, in assert_allclose
    assert_allclose(x_elt, y_elt, rtol, atol)
  File "/workspace/alpa/alpa/testing.py", line 42, in assert_allclose
    np.testing.assert_allclose(x, y, rtol, atol)
  File "/root/.cache/pypoetry/virtualenvs/tester-xS3fZVNL-py3.9/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 1527, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/root/.cache/pypoetry/virtualenvs/tester-xS3fZVNL-py3.9/lib/python3.9/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=0.0001, atol=0.0001

Mismatched elements: 1 / 1 (100%)
Max absolute difference: 0.64046633
Max relative difference: 0.4782978
 x: array(1.97952, dtype=float32)
 y: array(1.339054, dtype=float32)

======================================================================
FAIL: test_2_pipeline_parallel (__main__.InstallationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/alpa/alpa/test_install.py", line 65, in <module>
    runner.run(suite())
  File "/usr/lib/python3.9/unittest/runner.py", line 184, in run
    test(result)
  File "/usr/lib/python3.9/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.9/unittest/suite.py", line 122, in run
    test(result)
  File "/usr/lib/python3.9/unittest/case.py", line 651, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python3.9/unittest/case.py", line 592, in run
    self._callTestMethod(testMethod)
  File "/usr/lib/python3.9/unittest/case.py", line 550, in _callTestMethod
    method()
  File "/workspace/alpa/alpa/test_install.py", line 49, in test_2_pipeline_parallel
    actual_output = p_train_step(state, batch)
  File "/root/.cache/pypoetry/virtualenvs/tester-xS3fZVNL-py3.9/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/workspace/alpa/alpa/api.py", line 106, in __call__
    self._decode_args_and_get_executable(*args))
  File "/workspace/alpa/alpa/api.py", line 176, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/root/.cache/pypoetry/virtualenvs/tester-xS3fZVNL-py3.9/lib/python3.9/site-packages/jax/linear_util.py", line 272, in memoized_fun
    ans = call(fun, *args)
  File "/workspace/alpa/alpa/api.py", line 203, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/workspace/alpa/alpa/parallel_method.py", line 228, in compile_executable
    return compile_pipeshard_executable(
  File "/workspace/alpa/alpa/pipeline_parallel/compile_executable.py", line 77, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/workspace/alpa/alpa/pipeline_parallel/compile_executable.py", line 152, in compile_pipeshard_executable_internal
    manual_stage_option) = cluster_layers_and_slice_mesh(
  File "/workspace/alpa/alpa/pipeline_parallel/stage_construction.py", line 677, in cluster_layers_and_slice_mesh
    assert num_devices % num_stages == 0
jax._src.traceback_util.UnfilteredStackTrace: AssertionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/alpa/alpa/test_install.py", line 49, in test_2_pipeline_parallel
    actual_output = p_train_step(state, batch)
  File "/workspace/alpa/alpa/api.py", line 106, in __call__
    self._decode_args_and_get_executable(*args))
  File "/workspace/alpa/alpa/api.py", line 176, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/workspace/alpa/alpa/api.py", line 203, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/workspace/alpa/alpa/parallel_method.py", line 228, in compile_executable
    return compile_pipeshard_executable(
  File "/workspace/alpa/alpa/pipeline_parallel/compile_executable.py", line 77, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/workspace/alpa/alpa/pipeline_parallel/compile_executable.py", line 152, in compile_pipeshard_executable_internal
    manual_stage_option) = cluster_layers_and_slice_mesh(
  File "/workspace/alpa/alpa/pipeline_parallel/stage_construction.py", line 677, in cluster_layers_and_slice_mesh
    assert num_devices % num_stages == 0
AssertionError

----------------------------------------------------------------------
Ran 2 tests in 6.204s

FAILED (failures=2)
```
**Please describe the expected behavior**
Expect to pass the test

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): docker image "nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04"
- Python version: 3.9
- CUDA version: 11.2
- NCCL version: 8
- cupy version: 112
- GPU model and memory: NVIDIA GeForce RTX 3090 / 24576MiB
- Alpa version: 1.0.0.dev0
- TensorFlow version: N/A
- JAX version: 0.3.5

**To Reproduce**
DockerFile
```
### Start from NVIDIA deep learning base image
FROM nvidia/cuda:11.2.2-cudnn8-devel-ubuntu20.04

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

### New NVIDIA cuda package keys ###
RUN apt-key del "7fa2af80" \
&& export this_distro="$(cat /etc/os-release | grep '^ID=' | awk -F'=' '{print $2}')" \
&& export this_version="$(cat /etc/os-release | grep '^VERSION_ID=' | awk -F'=' '{print $2}' | sed 's/[^0-9]*//g')" \
&& apt-key adv --fetch-keys "https://developer.download.nvidia.com/compute/cuda/repos/${this_distro}${this_version}/x86_64/3bf863cc.pub" \
&& apt-key adv --fetch-keys "https://developer.download.nvidia.com/compute/machine-learning/repos/${this_distro}${this_version}/x86_64/7fa2af80.pub"

### Install general packages from apt-get ###
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y build-essential
RUN apt-get install -y tzdata
RUN apt-get install -y software-properties-common curl vim tmux git wget

### Install redis
RUN curl -fsSL https://packages.redis.io/gpg | gpg --dearmor -o /usr/share/keyrings/redis-archive-keyring.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/redis.list
RUN apt-get update && apt-get install -y redis
# Make redis modules directory
RUN mkdir /etc/redis/modules

## Build & install RedisJSON module
# Required dependencies to build RedisJSON
RUN apt-get install -y llvm cmake libclang1 libclang-dev cargo
# Clone RedisJSON
RUN mkdir /builds; cd /builds; git clone https://github.com/RedisJSON/RedisJSON.git;
# Build RedisJSON
RUN cd /builds/RedisJSON; cargo build --release;
# Move RedisJSON .so to redis modules directory
RUN mv /builds/RedisJSON/target/release/librejson.so /etc/redis/modules
# delete build directory
RUN rm -rf /builds

### python + pip3 install ###
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt-get install -y python3.9
RUN apt-get install -y python3.9-distutils
RUN apt-get install -y python3.9-dev
# v set python3.9 as default python3
RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 1
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.9
RUN pip3 install --upgrade pip
#############################

### BLAS + LAPACK + fortran compiler + llvm install ###
RUN apt-get install -y libblas-dev liblapack-dev gfortran llvm
### Install ILP for alpa ###
RUN apt-get install -y coinor-cbc
################################################

### python-poetry setup ###
ENV POETRY_HOME="/opt/poetry"
ENV POETRY_VERSION=1.1.13

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3.9 -
ENV PATH="$POETRY_HOME/bin:$PATH"
WORKDIR /workspace
COPY ./pyproject.toml ./
COPY ./alpa ./alpa/
#COPY ./poetry.lock ./
RUN poetry install -vvv
############################
RUN ls /workspace
```
In `pyproject.toml`
```
[tool.poetry]
name = "tester"
version = "0.1.0"
description = ""
authors = ["Ryan Benmalek <ryanai3@hotmail.com>"]

[tool.poetry.dependencies]
python = "~3.9"
alpa = {path="./alpa", develop=true}
pybind11 = "^2.10.0"
jaxlib = {url="https://github.com/alpa-projects/alpa/releases/download/v0.1.5/jaxlib-0.3.5%2Bcuda112.cudnn810-cp39-none-manylinux2010_x86_64.whl"}
cupy-cuda112 = "^10.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

Tried also using `pip` instead of `poetry`, and the same bug.

**Comment by zhisbug** [comment]
@JACKHAHA363 How many GPUs do you have? 

`assert num_devices % num_stages == 0` fails because the number of devices cannot be divided by the number of states you use.
