### ISSUE TITLE
Cannot generate database

### ISSUE THREAD

**Issue by zhiqi-0** [alpa-projects/alpa#666]
Hi, I'm trying to use Alpa at main branch. I'm trying the GPT model auto search but got a problem on generating database.

The command I use for the single node (8 x V100-16GB with DGX-1 topology):

```
$ ray start --head
$ python gen_prof_database.py --max-comm-size-intra-node 32 --max-comm-size-inter-node 29
```

And got the error:

```
Traceback (most recent call last):
  File "gen_prof_database.py", line 64, in <module>
    prof_database = cluster.profile_all(args.cluster_key,
  File "/opt/conda/lib/python3.8/site-packages/alpa/device_mesh.py", line 2112, in profile_all
    return mesh_profiling.profile_all(self, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/alpa/mesh_profiling.py", line 731, in profile_all
    dot_cost_dict = profile_dot(dot_range, device_cluster, cache_filename)
  File "/opt/conda/lib/python3.8/site-packages/alpa/mesh_profiling.py", line 638, in profile_dot
    physical_mesh = device_cluster.get_physical_mesh(host_ids=[0],
  File "/opt/conda/lib/python3.8/site-packages/alpa/device_mesh.py", line 2079, in get_physical_mesh
    return DistributedPhysicalDeviceMesh(
  File "/opt/conda/lib/python3.8/site-packages/alpa/device_mesh.py", line 943, in __init__
    self._launch_xla_servers()
  File "/opt/conda/lib/python3.8/site-packages/alpa/device_mesh.py", line 966, in _launch_xla_servers
    placement_group = retrieve_placement_group()
  File "/opt/conda/lib/python3.8/site-packages/alpa/util.py", line 1398, in retrieve_placement_group
    raise ValueError(
ValueError: The alpa training is not inside the ray tasks or actor or the placement group is not created yet. One reason is that Alpa is not connected to Ray cluster, and use `alpa.init('ray')` at the beginning. Do you have override the placement group? If not, please help file an issue on Github.
```

Then I changed the `gen_prof_database.py` by using `alpa.init('ray')` instead of `ray.init('auto')`, but it reports another error:

```
Traceback (most recent call last):
  File "gen_prof_database.py", line 61, in <module>
    cluster = DeviceCluster()
  File "/opt/conda/lib/python3.8/site-packages/alpa/device_mesh.py", line 2035, in __init__
    self.placement_group = create_placement_group(self.num_hosts,
  File "/opt/conda/lib/python3.8/site-packages/alpa/util.py", line 1322, in create_placement_group
    raise TimeoutError(
TimeoutError: Placement group creation timed out. Make sure your cluster either has enough resources or use an autoscaling cluster. If you are running on a cluster, make sure you specify an address in `ray.init()`, for example, `ray.init("auto")`. You can also increase the timeout by setting the ALPA_PLACEMENT_GROUP_TIMEOUT_S environment variable. Current resources available: {'GPU_group_6df6d50343ebf294baefe30ab6a203000000': 8.0, 'accelerator_type:V100': 1.0, 'node:10.4.34.139': 1.0, 'bundle_group_0_6df6d50343ebf294baefe30ab6a203000000': 1000.0, 'CPU': 39.0, 'memory': 480040942592.0, 'CPU_group_0_6df6d50343ebf294baefe30ab6a203000000': 1.0, 'GPU_group_0_6df6d50343ebf294baefe30ab6a203000000': 8.0, 'CPU_group_6df6d50343ebf294baefe30ab6a203000000': 1.0, 'bundle_group_6df6d50343ebf294baefe30ab6a203000000': 1000.0, 'object_store_memory': 200000000000.0}, resources requested by the placement group: [{'GPU': 8.0, 'CPU': 1.0}]
```

I checked ray status and it looks good:

```
======== Autoscaler status: 2022-08-22 01:10:30.641419 ========
Node status
---------------------------------------------------------------
Healthy:
 1 node_e4c811122584b75b7a927e0abd25e5a042bd3295818e04c10449b49d
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/40.0 CPU
 0.0/8.0 GPU
 0.0/1.0 accelerator_type:V100
 0.00/447.073 GiB memory
 0.00/186.265 GiB object_store_memory

Demands:
 (no resource demands)
```

And Alpa could run with a pre-found solution:

```
python benchmark.py --suite gpt.perf_test_auto
Working on case: BenchmarkCase(batch_size=1024, model_config=GPTModelConfig(seq_len=1024, hidden_size=2560, num_layers=32, num_heads=32, vocab_size=51200), num_micro_batches=128, parallel_mode='load_solution', parallel_args=LoadSolutionParallelArgs(prefer_reduce_scatter=True, use_remat=True, num_auto_layers=8, forward_stage_layer_ids=[[0, 1], [2, 3], [4, 5, 6, 7]], submesh_physical_shapes=[(1, 2), (1, 2), (1, 4)], submesh_logical_shapes=[(2, 1), (2, 1), (4, 1)], submesh_autosharding_option_dicts=[{'force_batch_dim_to_mesh_dim': 0}, {}, {}]))
 - Prepare input: 2.48 s
 - Create train state: 1.64 s
(MeshHostWorker pid=11051) NCCL version 2.11.4+cuda11.6
(MeshHostWorker pid=11049) NCCL version 2.11.4+cuda11.6
 - Compile (driver): 67.47 s
 - Compile (worker): 41.62 s
Iteration 0 ...
(MeshHostWorker pid=11053) NCCL version 2.9.9+cuda11.3
(MeshHostWorker pid=11049) NCCL version 2.9.9+cuda11.3
(MeshHostWorker pid=11051) NCCL version 2.9.9+cuda11.3
Iteration 1 ...
Iteration 2 ...
 - Benchmark: 149.41 s
Type: gpt  Model Config: GPTModelConfig(seq_len=1024, hidden_size=2560, num_layers=32, num_heads=32, vocab_size=51200)  #Microbatch: 128  #GPU: 8  Parallel Config: LoadSolutionParallelArgs(prefer_reduce_scatter=True, use_remat=True, num_auto_layers=8, forward_stage_layer_ids=[[0, 1], [2, 3], [4, 5, 6, 7]], submesh_physical_shapes=[(1, 2), (1, 2), (1, 4)], submesh_logical_shapes=[(2, 1), (2, 1), (4, 1)], submesh_autosharding_option_dicts=[{'force_batch_dim_to_mesh_dim': 0}, {}, {}])  Mean Time (s): 46.352  Std Time (s): 0.012  #Params (Billion): 2.649B  TFLOPs: 62.95  Peak Mem (GB): 11.221  Metadata: {'compilation_times': 'None', 'compute_cost_file_name': 'None', 'forward_stage_layer_ids': 'None', 'submesh_shapes': 'None', 'logical_mesh_shapes': 'None', 'autosharding_option_dicts': 'None'}
```

System information:

System: Ubuntu 20.04.3 LTS
CUDA version: 11.6
CUDNN: 8.3.2
The alpa installation is following pip install command, and the test reports no problem.

**Comment by merrymercy** [comment]
https://github.com/alpa-projects/alpa/pull/668

**Comment by zhiqi-0** [comment]
Great thanks! It works now.
