### ISSUE TITLE
Error installing 

### ISSUE THREAD

**Issue by saisurbehera** [alpa-projects/alpa#677]
Following error Installing cuda:

Building from source results with the following error:

Cuda 11.7
Cudann 8.20 

```
root@C.5077949:~/alpa/build_jaxlib$ python3 build/build.py --enable_cuda --dev_install --tf_path=$(pwd)/../third_party/tensorflow-alpa

     _   _  __  __
    | | / \ \ \/ /
 _  | |/ _ \ \  /
| |_| / ___ \/  \
 \___/_/   \/_/\_\


Downloading bazel from: https://github.com/bazelbuild/bazel/releases/download/5.1.0/bazel-5.1.0-linux-x86_64
bazel-5.1.0-linux-x86_64 [########################################] 100%
Bazel binary path: ./bazel-5.1.0-linux-x86_64
Bazel version: 5.1.0
Python binary path: /usr/bin/python3
Python version: 3.8
NumPy version: 1.22.4
MKL-DNN enabled: yes
Target CPU: x86_64
Target CPU features: release
CUDA enabled: yes
CUDA compute capabilities: 3.5,5.2,6.0,7.0,8.0
NCCL enabled: yes
TPU enabled: no
ROCm enabled: no

Building XLA and installing it in the jaxlib source tree...
./bazel-5.1.0-linux-x86_64 run --verbose_failures=true --config=avx_posix --config=mkl_open_source_only --config=cuda :build_wheel -- --output_path=/root/alpa/build_jaxlib/dist --cpu=x86_64 --dev_install
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=123
INFO: Reading rc options for 'run' from /root/alpa/build_jaxlib/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'run' from /root/alpa/build_jaxlib/.bazelrc:
  Inherited 'build' options: --apple_platform_type=macos --macos_minimum_os=10.9 --announce_rc --define open_source_build=true --spawn_strategy=standalone --enable_platform_specific_config --experimental_cc_shared_library --define=no_aws_support=true --define=no_gcp_support=true --define=no_hdfs_support=true --define=no_kafka_support=true --define=no_ignite_support=true --define=grpc_no_ares=true -c opt --config=short_logs --copt=-DMLIR_PYTHON_PACKAGE_PREFIX=jaxlib.mlir.
INFO: Reading rc options for 'run' from /root/alpa/build_jaxlib/.jax_configure.bazelrc:
  Inherited 'build' options: --strategy=Genrule=standalone --repo_env PYTHON_BIN_PATH=/usr/bin/python3 --action_env=PYENV_ROOT --python_path=/usr/bin/python3 --distinct_host_configuration=false --action_env TF_PATH=/root/alpa/build_jaxlib/../third_party/tensorflow-alpa --action_env TF_NCCL_VERSION=2.13.4
INFO: Found applicable config definition build:short_logs in file /root/alpa/build_jaxlib/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:avx_posix in file /root/alpa/build_jaxlib/.bazelrc: --copt=-mavx --host_copt=-mavx
INFO: Found applicable config definition build:mkl_open_source_only in file /root/alpa/build_jaxlib/.bazelrc: --define=tensorflow_mkldnn_contraction_kernel=1
INFO: Found applicable config definition build:cuda in file /root/alpa/build_jaxlib/.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,7.0,8.0 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --define=xla_python_enable_gpu=true
INFO: Found applicable config definition build:cuda in file /root/alpa/build_jaxlib/.jax_configure.bazelrc: --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,7.0,8.0
INFO: Found applicable config definition build:linux in file /root/alpa/build_jaxlib/.bazelrc: --config=posix --copt=-Wno-stringop-truncation --copt=-Wno-array-parameter
INFO: Found applicable config definition build:posix in file /root/alpa/build_jaxlib/.bazelrc: --copt=-fvisibility=hidden --copt=-Wno-sign-compare --cxxopt=-std=c++14 --host_cxxopt=-std=c++14
INFO: Repository local_config_cuda instantiated at:
  /root/alpa/build_jaxlib/WORKSPACE:47:14: in <toplevel>
  /root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/tensorflow/workspace2.bzl:869:19: in workspace
  /root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/tensorflow/workspace2.bzl:95:19:in _tf_toolchains
Repository rule cuda_configure defined at:
  /root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/gpus/cuda_configure.bzl:1448:33: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1076, column 27, in _create_local_cuda_repository
                cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 606, column 21, in _find_libs
                _check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 501, column 28, in _check_cuda_libs
                checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Expected even number of arguments
ERROR: /root/alpa/build_jaxlib/WORKSPACE:47:14: fetching cuda_configure rule //external:local_config_cuda: Traceback (mostrecent call last):
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1401, column 38, in _cuda_autoconf_impl
                _create_local_cuda_repository(repository_ctx)
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 1076, column 27, in _create_local_cuda_repository
                cuda_libs = _find_libs(repository_ctx, check_cuda_libs_script, cuda_config)
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 606, column 21, in _find_libs
                _check_cuda_libs(repository_ctx, check_cuda_libs_script, check_cuda_libs_params.values())
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/gpus/cuda_configure.bzl", line 501, column 28, in _check_cuda_libs
                checked_paths = execute(repository_ctx, [python_bin, "-c", cmd]).stdout.splitlines()
        File "/root/.cache/bazel/_bazel_root/8678d62e03fdc9a070cbd2b50f752f65/external/org_tensorflow/third_party/remote_config/common.bzl", line 230, column 13, in execute
                fail(
Error in fail: Repository command failed
Expected even number of arguments
INFO: Found applicable config definition build:cuda in file /root/alpa/build_jaxlib/.bazelrc: --repo_env TF_NEED_CUDA=1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=3.5,5.2,6.0,7.0,8.0 --crosstool_top=@local_config_cuda//crosstool:toolchain --@local_config_cuda//:enable_cuda --define=xla_python_enable_gpu=true
ERROR: @local_config_cuda//:enable_cuda :: Error loading option @local_config_cuda//:enable_cuda: Repository command failed
Expected even number of arguments

b''
Traceback (most recent call last):
  File "build/build.py", line 544, in <module>
    main()
  File "build/build.py", line 539, in main
    shell(command)
  File "build/build.py", line 53, in shell
    output = subprocess.check_output(cmd)
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['./bazel-5.1.0-linux-x86_64', 'run', '--verbose_failures=true', '--config=avx_posix', '--config=mkl_open_source_only', '--config=cuda', ':build_wheel', '--', '--output_path=/root/alpa/build_jaxlib/dist', '--cpu=x86_64', '--dev_install']' returned non-zero exit status 2.
````

**Comment by zhuohan123** [comment]
Can you try to compile with lower-version CUDA and CUDNN, for example, CUDA 11.2 and CUDNN 8.1.0? Does the error persist?

**Comment by saisurbehera** [comment]
I tried to compile using the pre-built alpa build and it works.

**Comment by zhuohan123** [comment]
Great! Let us know if meet any other issues.
