### ISSUE TITLE
time out error (Deadline Exceeded) when run python -m alpa.test_install

### ISSUE THREAD

**Issue by Sakura-gh** [alpa-projects/alpa#698]
**Please describe the bug**
I followed the install instructions in [tutorial](https://alpa.ai/install.html), and all things seems to be ok. But when I followed **Check Installation** section, use `python -m alpa.test_install`, then meet the time out error (**Deadline Exceeded**) unfortunately. so can anyone give some suggestions?

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Ubuntu 18.04
- Python version: 3.7.13
- CUDA version: 11.1
- NCCL version: 2.10.3
- cupy version: 11.1.0
- GPU model and memory: 8×Tesla P100-PCIE-16GB
- Alpa version: 0.2.0
- TensorFlow version: 2.10.0
- JAX version: 0.3.15
- JAXlib version: 0.3.15+cuda111.cudnn805

**To Reproduce**
1. python -m alpa.test_install

**Error Info**
~~~bash
(alpa) root@28c67ac89ed8:/home/gehao/Alpa/alpa# python -m alpa.test_install.py
.2022-09-13 09:33:09,527        INFO worker.py:1333 -- Connecting to existing Ray cluster at address: 172.17.0.3:6379...
2022-09-13 09:33:09,539 INFO worker.py:1518 -- Connected to Ray cluster.
E
======================================================================
ERROR: test_2_pipeline_parallel (alpa.test_install.InstallationTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/runtime/test_install.py", line 7, in <module>
    runner.run(suite())
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/unittest/runner.py", line 176, in run
    test(result)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/unittest/suite.py", line 84, in __call__
    return self.run(*args, **kwds)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/unittest/suite.py", line 122, in run
    test(result)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/unittest/case.py", line 676, in __call__
    return self.run(*args, **kwds)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/unittest/case.py", line 628, in run
    testMethod()
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/test_install.py", line 49, in test_2_pipeline_parallel
    actual_output = p_train_step(state, batch)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/api.py", line 118, in __call__
    self._decode_args_and_get_executable(*args))
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/api.py", line 191, in _decode_args_and_get_executable
    self.method, *abstract_args)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/jax/linear_util.py", line 295, in memoized_fun
    ans = call(fun, *args)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/api.py", line 217, in _compile_parallel_executable
    batch_invars, *avals)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/parallel_method.py", line 236, in compile_executable
    self.stage_input_shardings, *avals)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/compile_executable.py", line 96, in compile_pipeshard_executable
    None, stage_input_shardings)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/compile_executable.py", line 268, in compile_pipeshard_executable_internal
    allreduce_groups=allreduce_groups).compile()
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 400, in compile
    self._compile_resharding_tasks()
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 340, in _compile_resharding_tasks
    dst_mesh)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 195, in __init__
    self._compile()
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 220, in _compile
    self.put_all_tasks()
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 240, in put_all_tasks
    ray.get(task_dones)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
jax._src.traceback_util.UnfilteredStackTrace: ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=136957, ip=172.17.0.3, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f69ee88ee10>)
  File "/home/gehao/Alpa/alpa/alpa/device_mesh.py", line 126, in __init__
    self.distributed_client.connect()
jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: DEADLINE_EXCEEDED: Deadline Exceeded

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/test_install.py", line 49, in test_2_pipeline_parallel
    actual_output = p_train_step(state, batch)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/compile_executable.py", line 96, in compile_pipeshard_executable
    None, stage_input_shardings)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/compile_executable.py", line 268, in compile_pipeshard_executable_internal
    allreduce_groups=allreduce_groups).compile()
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 400, in compile
    self._compile_resharding_tasks()
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/runtime_emitter.py", line 340, in _compile_resharding_tasks
    dst_mesh)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 195, in __init__
    self._compile()
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 220, in _compile
    self.put_all_tasks()
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/alpa/pipeline_parallel/cross_mesh_resharding.py", line 240, in put_all_tasks
    ray.get(task_dones)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/gehao/anaconda3/envs/alpa/lib/python3.7/site-packages/ray/_private/worker.py", line 2277, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=136957, ip=172.17.0.3, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f69ee88ee10>)
  File "/home/gehao/Alpa/alpa/alpa/device_mesh.py", line 126, in __init__
    self.distributed_client.connect()
jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: DEADLINE_EXCEEDED: Deadline Exceeded

----------------------------------------------------------------------
Ran 2 tests in 141.608s

FAILED (errors=1)
(MeshHostWorker pid=136957) 2022-09-13 09:35:18.893979: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:215] Connect() failed after 1 retries in 0; most recent failure status: DEADLINE_EXCEEDED: Deadline Exceeded
(MeshHostWorker pid=136957) 2022-09-13 09:35:18,896     ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=136957, ip=172.17.0.3, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f69ee88ee10>)
(MeshHostWorker pid=136957)   File "/home/gehao/Alpa/alpa/alpa/device_mesh.py", line 126, in __init__
(MeshHostWorker pid=136957)     self.distributed_client.connect()
(MeshHostWorker pid=136957) jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: DEADLINE_EXCEEDED: Deadline Exceeded
(MeshHostWorker pid=136956) 2022-09-13 09:35:18.950654: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:215] Connect() failed after 1 retries in 0; most recent failure status: DEADLINE_EXCEEDED: Deadline Exceeded
(MeshHostWorker pid=136956) 2022-09-13 09:35:18,952     ERROR worker.py:756 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=136956, ip=172.17.0.3, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f27f9795b50>)
(MeshHostWorker pid=136956)   File "/home/gehao/Alpa/alpa/alpa/device_mesh.py", line 126, in __init__
(MeshHostWorker pid=136956)     self.distributed_client.connect()
(MeshHostWorker pid=136956) jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: DEADLINE_EXCEEDED: Deadline Exceeded
~~~

**Comment by zhisbug** [comment]
@Sakura-gh what's your ray version?

**Comment by Sakura-gh** [comment]
> @Sakura-gh what's your ray version?

ray version: 2.0.0

**Comment by zhisbug** [comment]
@Sakura-gh please use ray==1.xx, e.g., 1.18/
Ray 2.0 was released very recently but not tested on Alpa yet.

**Comment by Sakura-gh** [comment]
> @Sakura-gh please use ray==1.xx, e.g., 1.18 Ray 2.0 was released very recently but not tested on Alpa yet.

I tried ray==1.30 (1.xx newest version=1.30), but the `Connect() timed out` error still exists.
~~~bash
ERROR: Could not find a version that satisfies the requirement ray==1.18 (from versions: 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 1.0.0rc0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1, 1.0.1.post1, 1.1.0, 1.2.0, 1.3.0, 1.4.0rc1, 1.4.0rc2, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.5.2, 1.6.0, 1.7.0rc0, 1.7.0, 1.7.1, 1.8.0, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.9.1rc0, 1.9.1, 1.9.2, 1.10.0rc0, 1.10.0, 1.11.0rc0, 1.11.0rc1, 1.11.0, 1.11.1, 1.12.0rc1, 1.12.0, 1.12.1, 1.13.0, 2.0.0rc0, 2.0.0rc1, 2.0.0)
~~~ 

I found that the error info: ` E external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:215] Connect() failed after 1 retries in 0; most recent failure status: DEADLINE_EXCEEDED: Deadline Exceeded`, and I used the tensorflow==1.10.0, is the tensorflow version suitable?

**Comment by zhisbug** [comment]
@Sakura-gh try ray == 1.13? see ray versions: https://pypi.org/project/ray/#history

**Comment by Sakura-gh** [comment]
> @Sakura-gh try ray == 1.13? see ray versions: https://pypi.org/project/ray/#history
@zhisbug I've tried ray==1.13, just type wrong.
> I tried ray==1.13 (1.xx newest version=1.13), but the Connect() timed out error still exists.

**Comment by zhisbug** [comment]
alpa does not have a Tensorflow dependency. Could you follow alpa installation doc?

**Comment by Sakura-gh** [comment]
> alpa does not have a Tensorflow dependency. Could you follow alpa installation doc?

@zhisbug yes, I followed the alpa installation doc, I just do:
~~~bash
conda create -n alpa_test python=3.7
conda activate alpa_test
pip3 install cupy-cuda111
python3 -c "from cupy.cuda import nccl"
pip3 install alpa
pip3 install ray==1.13.0
pip3 install jaxlib==0.3.15+cuda111.cudnn805 -f https://alpa-projects.github.io/wheels.html
ray start --head --port=60076
python3 -m test_install.py
~~~
then `Connect() timed out` error happens.

conda list:
~~~bash
(alpa_test) root@28c67ac89ed8:~# conda list
# packages in environment at /home/gehao/anaconda3/envs/alpa_test:
#
# Name                    Version                   Build  Channel
absl-py                   1.2.0                     <pip>
aiosignal                 1.2.0                     <pip>
alpa                      0.2.0                     <pip>
attrs                     22.1.0                    <pip>
ca-certificates           2022.07.19           h06a4308_0
certifi                   2022.6.15        py37h06a4308_0
charset-normalizer        2.1.1                     <pip>
chex                      0.1.4                     <pip>
click                     8.0.4                     <pip>
colorama                  0.4.5                     <pip>
commonmark                0.9.1                     <pip>
cupy-cuda111              11.1.0                    <pip>
cycler                    0.11.0                    <pip>
distlib                   0.3.6                     <pip>
dm-tree                   0.1.7                     <pip>
etils                     0.8.0                     <pip>
fastrlock                 0.8                       <pip>
filelock                  3.8.0                     <pip>
flax                      0.5.2                     <pip>
fonttools                 4.37.1                    <pip>
frozenlist                1.3.1                     <pip>
grpcio                    1.43.0                    <pip>
idna                      3.4                       <pip>
importlib-metadata        4.12.0                    <pip>
importlib-resources       5.9.0                     <pip>
jax                       0.3.15                    <pip>
jaxlib                    0.3.15+cuda111.cudnn805           <pip>
jsonschema                4.16.0                    <pip>
kiwisolver                1.4.4                     <pip>
ld_impl_linux-64          2.38                 h1181459_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 11.2.0               h1234567_1
libstdcxx-ng              11.2.0               h1234567_1
llvmlite                  0.39.1                    <pip>
matplotlib                3.5.3                     <pip>
msgpack                   1.0.4                     <pip>
ncurses                   6.3                  h5eee18b_3
numba                     0.56.2                    <pip>
numpy                     1.21.6                    <pip>
openssl                   1.1.1q               h7f8727e_0
opt-einsum                3.3.0                     <pip>
optax                     0.1.3                     <pip>
packaging                 21.3                      <pip>
Pillow                    9.2.0                     <pip>
pip                       22.1.2           py37h06a4308_0
pkgutil_resolve_name      1.3.10                    <pip>
platformdirs              2.5.2                     <pip>
protobuf                  3.20.2                    <pip>
PuLP                      2.6.0                     <pip>
Pygments                  2.13.0                    <pip>
pyparsing                 3.0.9                     <pip>
pyrsistent                0.18.1                    <pip>
python                    3.7.13               h12debd9_0
python-dateutil           2.8.2                     <pip>
PyYAML                    6.0                       <pip>
ray                       1.13.0                    <pip>
readline                  8.1.2                h7f8727e_1
requests                  2.28.1                    <pip>
rich                      11.2.0                    <pip>
scipy                     1.7.3                     <pip>
setuptools                63.4.1           py37h06a4308_0
setuptools                59.8.0                    <pip>
six                       1.16.0                    <pip>
sqlite                    3.39.2               h5082296_0
tk                        8.6.12               h1ccaba5_0
toolz                     0.12.0                    <pip>
tqdm                      4.64.1                    <pip>
typing_extensions         4.3.0                     <pip>
urllib3                   1.26.12                   <pip>
virtualenv                20.16.5                   <pip>
wheel                     0.37.1             pyhd3eb1b0_0
xz                        5.2.5                h7f8727e_1
zipp                      3.8.1                     <pip>
zlib                      1.2.12               h5eee18b_3
~~~

**Comment by zhisbug** [comment]
could you try not to set the port when you start ray?

**Comment by Sakura-gh** [comment]
> could you try not to set the port when you start ray?

the result keeps the same, emo...

**Comment by merrymercy** [comment]
closed due to inactivity

**Comment by Mika-Gu** [comment]
> 

Have you solve this problem? I got th same error...

**Comment by Sakura-gh** [comment]
> > 
> 
> Have you solved this problem?

not yet.

**Comment by RuoyuChen10** [comment]
> > > 
> > 
> > 
> > Have you solved this problem?
> 
> not yet.

you should install:

```
pip install ray==1.13.0
```

not `1.13`

**Comment by vectercyg** [comment]
I also encountered this problem. Is there a solution?

**Comment by mika-gu** [comment]
> > 
> 
> Have you solved this problem?

My problem is: I init alpa at all workers. The right way is  just init at wotker-0

**Comment by dmaksimo** [comment]
> > > 
> > 
> > 
> > Have you solved this problem?
> 
> My problem is: I init alpa at all workers. The right way is just init at wotker-0

@mika-gu , how did you solve the issue exactly? I would much appreciated. I am fighting with the same issue.

**Comment by dmaksimo** [comment]
FYI. I spent days figuring out what is wrong, if you experience the same issue most likely your gRPC connection is failed. Unset http_proxy / https_proxy so packets flows properly https://github.com/google/jax/discussions/9582 or configure properly iptables
