### ISSUE TITLE
Install Test Failed

### ISSUE THREAD

**Issue by dumpmemory** [alpa-projects/alpa#794]
**Please describe the bug**
After build Docker image , i run python3 -m alpa.test_install , but it print the failed message:

`sh-4.2# python3 -m alpa.test_install
2022-12-02 10:35:50.125351: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:85] Couldn't get ptxas version string: INTERNAL: Running ptxas --version returned 32512
2022-12-02 10:35:50.164959: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:454] ptxas returned an error during compilation of ptx to sass: 'INTERNAL: ptxas exited with non-zero error code 32512, output: '  If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.
Aborted (core dumped)`

**Please describe the expected behavior**

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Docker based on nvidia/cuda:11.3.1-cudnn8-runtime-centos7
- Python version: 3.8
- CUDA version: 11.3
- NCCL version: 820
- cupy version: cupy-cuda113
- GPU model and memory: 2080ti 11g
- Alpa version: 0.2.2
- TensorFlow version: 2.1.0
- JAX version: `0.3.22+cuda113.cudnn820`

**To Reproduce**

I have modified the https://github.com/alpa-projects/alpa/blob/75f3597dbf4a49debce3cc1a8c83f2cb7b8b6eda/alpa/device_mesh.py#L2153 line, to pass the node which don't have any gpus. 

Then I tried to train a gpt-neo 125M parameters model using the code https://github.com/alpa-projects/alpa/blob/main/examples/gpt2/run_clm_flax.py on 2 nodes, one head node which don't have any cpus or gpus and one worker node has 8 gpus showing the following error:

~~~
{'accelerator_type:G': 2.0, 'node:10.32.21.8': 1.0, 'memory': 240518168575.0, 'object_store_memory': 102965547417.0, 'CPU': 72.0, 'GPU': 8.0, 'node:10.32.13.122': 1.0}
INFO:__main__:Training/evaluation parameters TrainingArguments(output_dir='/mnt/train/test_norwegian-gpt-neo', overwrite_output_dir=True, do_train=True, do_eval=True, per_device_train_batch_size=16, per_device_eval_batch_size=1, num_micro_batches=16, learning_rate=0.001, weight_decay=0.01, adam_beta1=0.9, adam_beta2=0.98, adam_epsilon=1e-08, adafactor=False, num_train_epochs=20.0, warmup_steps=1000, logging_steps=100, save_steps=2500, eval_steps=2500, seed=42, push_to_hub=False, hub_model_id=None, hub_token=None)
WARNING:datasets.builder:Using custom data configuration default-b798866ccd0da4e0
WARNING:datasets.builder:Reusing dataset json (/mnt/train/huggingface_cache/datasets/json/default-b798866ccd0da4e0/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253)

  0%|          | 0/2 [00:00<?, ?it/s]
100%|██████████| 2/2 [00:00<00:00, 140.89it/s]
loading configuration file /mnt/train/pretrain_model/models--EleutherAI--gpt-neo-125M/snapshots/324e21bd3b56dfecba4308ab6ec147b588df23af/config.json
Model config GPTNeoConfig {
  "_name_or_path": "/mnt/train/pretrain_model/models--EleutherAI--gpt-neo-125M/snapshots/324e21bd3b56dfecba4308ab6ec147b588df23af/",
  "activation_function": "gelu_new",
  "architectures": [
    "GPTNeoForCausalLM"
  ],
  "attention_dropout": 0,
  "attention_layers": [
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local"
  ],
  "attention_types": [
    [
      [
        "global",
        "local"
      ],
      6
    ]
  ],
  "bos_token_id": 50256,
  "embed_dropout": 0,
  "eos_token_id": 50256,
  "gradient_checkpointing": false,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": null,
  "layer_norm_epsilon": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "gpt_neo",
  "num_heads": 12,
  "num_layers": 12,
  "resid_dropout": 0,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "transformers_version": "4.24.0",
  "use_cache": true,
  "vocab_size": 50257,
  "window_size": 256
}

loading configuration file /mnt/train/pretrain_model/models--EleutherAI--gpt-neo-125M/snapshots/324e21bd3b56dfecba4308ab6ec147b588df23af/config.json
Model config GPTNeoConfig {
  "_name_or_path": "/mnt/train/pretrain_model/models--EleutherAI--gpt-neo-125M/snapshots/324e21bd3b56dfecba4308ab6ec147b588df23af/",
  "activation_function": "gelu_new",
  "architectures": [
    "GPTNeoForCausalLM"
  ],
  "attention_dropout": 0,
  "attention_layers": [
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local"
  ],
  "attention_types": [
    [
      [
        "global",
        "local"
      ],
      6
    ]
  ],
  "bos_token_id": 50256,
  "embed_dropout": 0,
  "eos_token_id": 50256,
  "gradient_checkpointing": false,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": null,
  "layer_norm_epsilon": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "gpt_neo",
  "num_heads": 12,
  "num_layers": 12,
  "resid_dropout": 0,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "transformers_version": "4.24.0",
  "use_cache": true,
  "vocab_size": 50257,
  "window_size": 256
}

loading file vocab.json
loading file merges.txt
loading file tokenizer.json
loading file added_tokens.json
loading file special_tokens_map.json
loading file tokenizer_config.json
loading configuration file /mnt/train/pretrain_model/models--EleutherAI--gpt-neo-125M/snapshots/324e21bd3b56dfecba4308ab6ec147b588df23af/config.json
Model config GPTNeoConfig {
  "_name_or_path": "/mnt/train/pretrain_model/models--EleutherAI--gpt-neo-125M/snapshots/324e21bd3b56dfecba4308ab6ec147b588df23af/",
  "activation_function": "gelu_new",
  "architectures": [
    "GPTNeoForCausalLM"
  ],
  "attention_dropout": 0,
  "attention_layers": [
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local"
  ],
  "attention_types": [
    [
      [
        "global",
        "local"
      ],
      6
    ]
  ],
  "bos_token_id": 50256,
  "embed_dropout": 0,
  "eos_token_id": 50256,
  "gradient_checkpointing": false,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": null,
  "layer_norm_epsilon": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "gpt_neo",
  "num_heads": 12,
  "num_layers": 12,
  "resid_dropout": 0,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "transformers_version": "4.24.0",
  "use_cache": true,
  "vocab_size": 50257,
  "window_size": 256
}

loading configuration file /mnt/train/pretrain_model/models--EleutherAI--gpt-neo-125M/snapshots/324e21bd3b56dfecba4308ab6ec147b588df23af/config.json
Model config GPTNeoConfig {
  "_name_or_path": "/mnt/train/pretrain_model/models--EleutherAI--gpt-neo-125M/snapshots/324e21bd3b56dfecba4308ab6ec147b588df23af/",
  "activation_function": "gelu_new",
  "architectures": [
    "GPTNeoForCausalLM"
  ],
  "attention_dropout": 0,
  "attention_layers": [
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local",
    "global",
    "local"
  ],
  "attention_types": [
    [
      [
        "global",
        "local"
      ],
      6
    ]
  ],
  "bos_token_id": 50256,
  "embed_dropout": 0,
  "eos_token_id": 50256,
  "gradient_checkpointing": false,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": null,
  "layer_norm_epsilon": 1e-05,
  "max_position_embeddings": 2048,
  "model_type": "gpt_neo",
  "num_heads": 12,
  "num_layers": 12,
  "resid_dropout": 0,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "transformers_version": "4.24.0",
  "use_cache": true,
  "vocab_size": 50257,
  "window_size": 256
}

INFO:__main__:***** Tokenize dataset *****
WARNING:datasets.arrow_dataset:Loading cached processed dataset at /mnt/train/huggingface_cache/datasets/json/default-b798866ccd0da4e0/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253/cache-b9c946736681ecf8.arrow
WARNING:datasets.arrow_dataset:Loading cached processed dataset at /mnt/train/huggingface_cache/datasets/json/default-b798866ccd0da4e0/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253/cache-eca30e657e8a7364.arrow
INFO:__main__:***** Build dataset *****
WARNING:datasets.arrow_dataset:Loading cached processed dataset at /mnt/train/huggingface_cache/datasets/json/default-b798866ccd0da4e0/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253/cache-c40ce249fd4e3e96.arrow
WARNING:datasets.arrow_dataset:Loading cached processed dataset at /mnt/train/huggingface_cache/datasets/json/default-b798866ccd0da4e0/0.0.0/a3e658c4731e59120d44081ac10bf85dc7e1388126b92338344ce9661907f253/cache-37cc1357dec3e07f.arrow
INFO:__main__:***** Running training *****
INFO:__main__:  Num examples = 34796
INFO:__main__:  Num Epochs = 20
INFO:__main__:  Batch size per device (w. accumulation) = 16
INFO:__main__:  Global train batch size (w. parallel & distributed) = 32
INFO:__main__:  Total optimization steps = 21740

Epoch ... :   0%|          | 0/20 [00:00<?, ?it/s]

Initial compilation. This might take some minutes...

Epoch ... :   0%|          | 0/20 [00:00<?, ?it/s]
                                                     (MeshHostWorker pid=929, ip=10.32.13.122) 2022-12-02 00:54:56.741816: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:85] Couldn't get ptxas version string: INTERNAL: Running ptxas --version returned 32512
(MeshHostWorker pid=929, ip=10.32.13.122) 2022-12-02 00:54:56.765987: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/redzone_allocator.cc:318] INTERNAL: ptxas exited with non-zero error code 32512, output:
(MeshHostWorker pid=929, ip=10.32.13.122) Relying on driver to perform ptx compilation.
(MeshHostWorker pid=929, ip=10.32.13.122) Modify $PATH to customize ptxas location.
(MeshHostWorker pid=929, ip=10.32.13.122) This message will be only logged once.
(MeshHostWorker pid=929, ip=10.32.13.122) 2022-12-02 00:54:56.835136: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:85] Couldn't get ptxas version string: INTERNAL: Running ptxas --version returned 32512
(MeshHostWorker pid=929, ip=10.32.13.122) 2022-12-02 00:54:56.859478: W external/org_tensorflow/tensorflow/compiler/xla/service/gpu/buffer_comparator.cc:641] INTERNAL: ptxas exited with non-zero error code 32512, output:
(MeshHostWorker pid=929, ip=10.32.13.122) Relying on driver to perform ptx compilation.
(MeshHostWorker pid=929, ip=10.32.13.122) Setting XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda  or modifying $PATH can be used to set the location of ptxas
(MeshHostWorker pid=929, ip=10.32.13.122) This message will only be logged once.
(MeshHostWorker pid=929, ip=10.32.13.122) 2022-12-02 00:55:00.984332: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:85] Couldn't get ptxas version string: INTERNAL: Running ptxas --version returned 32512
(MeshHostWorker pid=929, ip=10.32.13.122) 2022-12-02 00:55:01.010587: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:85] Couldn't get ptxas version string: INTERNAL: Running ptxas --version returned 32512
(MeshHostWorker pid=929, ip=10.32.13.122) 2022-12-02 00:55:01.023445: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:454] ptxas returned an error during compilation of ptx to sass: 'INTERNAL: ptxas exited with non-zero error code 32512, output: '  If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.
(MeshHostWorker pid=929, ip=10.32.13.122) *** SIGABRT received at time=1669913701 on cpu 17 ***
(MeshHostWorker pid=929, ip=10.32.13.122) PC: @     0x7f0a5461e387  (unknown)  raise
(MeshHostWorker pid=929, ip=10.32.13.122)     @     0x7f0a549c5630       3632  (unknown)
(MeshHostWorker pid=929, ip=10.32.13.122)     @     0x7ef6b1f4cc71       2128  xla::gpu::NVPTXCompiler::CompileGpuAsmOrGetCachedResult()
(MeshHostWorker pid=929, ip=10.32.13.122)     @     0x7ef6b3133b10       2800  xla::gpu::NVPTXCompiler::CompileTargetBinary()
(MeshHostWorker pid=929, ip=10.32.13.122)     @     0x7ef6b317a0f2        784  xla::gpu::GpuCompiler::CompileToTargetBinary()::{lambda()#1}::operator()()
(MeshHostWorker pid=929, ip=10.32.13.122)     @     0x7ef6b3183a0a        864  xla::gpu::GpuCompiler::CompileToTargetBinary()::{lambda()#3}::operator()()
(MeshHostWorker pid=929, ip=10.32.13.122) 2022-12-02 00:55:01.051253: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:454] ptxas returned an error during compilation of ptx to sass: 'INTERNAL: ptxas exited with non-zero error code 32512, output: '  If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.
(MeshHostWorker pid=929, ip=10.32.13.122) [failure_signal_handler.cc : 331] RAW: Signal 6 raised at PC=0x7f0a5461e387 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=929, ip=10.32.13.122)     @     0x7ef6b70f70cb        176  Eigen::ThreadPoolTempl<>::WorkerLoop()
(MeshHostWorker pid=929, ip=10.32.13.122)     @     0x7ef6b70f4a03         64  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=929, ip=10.32.13.122) 2022-12-02 00:55:01.068424: W external/org_tensorflow/tensorflow/compiler/xla/stream_executor/gpu/asm_compiler.cc:85] Couldn't get ptxas version string: INTERNAL: Running ptxas --version returned 32512
(MeshHostWorker pid=929, ip=10.32.13.122)     @     0x7ef6b70e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=929, ip=10.32.13.122)     @     0x7f0a549bdea5  (unknown)  start_thread
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,068 E 929 1090] logging.cc:361: *** SIGABRT received at time=1669913701 on cpu 17 ***
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,079 E 929 1090] logging.cc:361: PC: @     0x7f0a5461e387  (unknown)  raise
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,079 E 929 1090] logging.cc:361:     @     0x7f0a549c5630       3632  (unknown)
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,080 E 929 1090] logging.cc:361:     @     0x7ef6b1f4cc71       2128  xla::gpu::NVPTXCompiler::CompileGpuAsmOrGetCachedResult()
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,080 E 929 1090] logging.cc:361:     @     0x7ef6b3133b10       2800  xla::gpu::NVPTXCompiler::CompileTargetBinary()
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,080 E 929 1090] logging.cc:361:     @     0x7ef6b317a0f2        784  xla::gpu::GpuCompiler::CompileToTargetBinary()::{lambda()#1}::operator()()
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,080 E 929 1090] logging.cc:361:     @     0x7ef6b3183a0a        864  xla::gpu::GpuCompiler::CompileToTargetBinary()::{lambda()#3}::operator()()
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,080 E 929 1090] logging.cc:361:     @     0x7ef6b70f70cb        176  Eigen::ThreadPoolTempl<>::WorkerLoop()
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,080 E 929 1090] logging.cc:361:     @     0x7ef6b70f4a03         64  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,080 E 929 1090] logging.cc:361:     @     0x7ef6b70e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=929, ip=10.32.13.122) [2022-12-02 00:55:01,080 E 929 1090] logging.cc:361:     @     0x7f0a549bdea5  (unknown)  start_thread
(MeshHostWorker pid=929, ip=10.32.13.122) Fatal Python error: Aborted
(MeshHostWorker pid=929, ip=10.32.13.122)



2022-12-02 00:56:26,141	WARNING worker.py:1839 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff88bbd618ddcd9c812d809b9f15000000 Worker ID: 6bac86ef7c90192ddbe594fbeea854f230bcf6aa9f5f16bb26cbbf64 Node ID: ed259211e1012aeb82e042248057aa7958b9ee82da5977bd4b221982 Worker IP address: 10.32.13.122 Worker port: 10019 Worker PID: 929 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.


Epoch ... :   0%|          | 0/20 [01:54<?, ?it/s]
Traceback (most recent call last):
  File "run_clm_jax.py", line 826, in <module>
    main()
  File "run_clm_jax.py", line 712, in main
    executable.sync()
  File "/home/nlp/miniconda/lib/python3.8/site-packages/alpa/mesh_executable.py", line 114, in sync
    self.physical_mesh.sync_workers()
  File "/home/nlp/miniconda/lib/python3.8/site-packages/alpa/device_mesh.py", line 1370, in sync_workers
    ray.get([w.sync.remote() for w in self.workers])
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/worker.py", line 2291, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: MeshHostWorker
	actor_id: 88bbd618ddcd9c812d809b9f15000000
	pid: 929
	namespace: 324a2d1c-3b76-4e86-b592-34b05710c22f
	ip: 10.32.13.122
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

---------------------------------------
Job 'raysubmit_q2nsSaF1kBAeaAEB' failed
---------------------------------------

Status message: Job failed due to an application error, last available logs (truncated to 20,000 chars):
    return func(*args, **kwargs)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/worker.py", line 2291, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: MeshHostWorker
	actor_id: 88bbd618ddcd9c812d809b9f15000000
	pid: 929
	namespace: 324a2d1c-3b76-4e86-b592-34b05710c22f
	ip: 10.32.13.122
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
~~~

**Comment by dumpmemory** [comment]
pass python3 -m alpa.test_install by changing base image to nvidia/cuda:11.3.1-cudnn8-devel-centos7
