### ISSUE TITLE
get_merged_stages_memory_stats ValueError: cannot convert float NaN to integer

### ISSUE THREAD

**Issue by dumpmemory** [alpa-projects/alpa#810]
**Please describe the bug**
when i use 125m gpt-neo with following 

```
method = alpa.PipeshardParallel(num_micro_batches=training_args.num_micro_batches,
                                        layer_option=alpa.AutoLayerOption(layer_num=2),
                                                                            stage_option="auto")
```
it failed with following error:

```
Traceback (most recent call last):
  File "run_clm_jax.py", line 832, in <module>
    main()
  File "run_clm_jax.py", line 712, in main
    state, train_metric = p_train_step(state, batch)
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 95, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 155, in compile_pipeshard_executable_internal
    manual_stage_option) = cluster_layers_and_slice_mesh(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/stage_construction.py", line 623, in cluster_layers_and_slice_mesh
    compute_cost, max_n_succ_stages = get_compute_cost(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/stage_profiling.py", line 1310, in get_compute_cost
    max_n_succ_stages) = interpret_profile_result_training_2d(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/stage_profiling.py", line 940, in interpret_profile_result_training_2d
    get_merged_stages_memory_stats([profile_result]))
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/stage_profiling.py", line 910, in get_merged_stages_memory_stats
    max_stage = int((available_memory - peak_memory - initial_size) //
ValueError: cannot convert float NaN to integer
```
**Please describe the expected behavior**

should find a way to compile. I found the inf number is from peak_memory. 

System information and environment

OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Docker based on nvidia/cuda:11.3.1-cudnn8-devel-centos7
Python version: 3.8
CUDA version: 11.3
NCCL version: 820
cupy version: cupy-cuda113
GPU model and memory: 2080ti 11g
Alpa version: install from source
TensorFlow version: 2.1.0
JAX version: 0.3.22+cuda113.cudnn820

**To Reproduce**
1. run  https://github.com/alpa-projects/alpa/blob/main/examples/gpt2/run_clm_flax.py
2.
3.

**Screenshots**

**Code snippet to reproduce the problem**

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by zhisbug** [comment]
It seems when Alpa run the profiling, some values failed to be returned. Please comment? @zhuohan123

**Comment by dumpmemory** [comment]
Here is one running log which showing some inf values
result[(0, 1, 3, 2), 0] = ModuleProfileResult(compute_cost=inf, peak_memory=inf GB, invar_size=0.112 GB, outvar_size=1.596 GB, temp_buffer_size=inf GB, available_memory=0.000 GB)

Epoch ... :   0%|          | 0/20 [02:02<?, ?it/s]

Training...:   0%|          | 0/271 [02:02<?, ?it/s]

**Comment by dumpmemory** [comment]
Now for running gpt-neo 125m with [run_clm_flax.py](https://github.com/alpa-projects/alpa/blob/main/examples/gpt2/run_clm_flax.py), it seems that alpa can found a profile setting , but failed after that. 
```
Profile result saved to: profile-results-2022-12-19-19-36-38.npy
----------------------------------------------------------------------
Result forward_stage_layer_ids: [[0], [1]]
Result mesh_shapes: [(1, 4), (1, 4)]
Result logical_mesh_shapes: [(4, 1), (4, 1)]
Result autosharding_option_dicts: [{'force_batch_dim_to_mesh_dim': 0}, {}]
2022-12-19 19:37:04,734	WARNING worker.py:1851 -- It looks like you're creating a detached actor in an anonymous namespace. In order to access this actor in the future, you will need to explicitly connect to this namespace with ray.init(namespace="a88d5230-77eb-4105-9d51-3dc734672a7e", ...)
(MeshHostWorker pid=10617, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f98a3c03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10617, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f98a3c03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10617, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f98a3c03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10617, ip=10.32.10.64) *** SIGSEGV received at time=1671449853 on cpu 64 ***
(MeshHostWorker pid=10617, ip=10.32.10.64) PC: @     0x7f98a3c03558  (unknown)  xla::gpu::CrossMeshNcclAllReduceThunk::ExecuteOnStream()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7fac4562e630       4016  (unknown)
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a3b9adae        800  xla::gpu::(anonymous namespace)::ExecuteThunks()
(MeshHostWorker pid=10615, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f7a0bc03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10615, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f7a0bc03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10615, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f7a0bc03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10615, ip=10.32.10.64) *** SIGSEGV received at time=1671449853 on cpu 45 ***
(MeshHostWorker pid=10615, ip=10.32.10.64) PC: @     0x7f7a0bc03558  (unknown)  xla::gpu::CrossMeshNcclAllReduceThunk::ExecuteOnStream()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f8dac4eb630       4016  (unknown)
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0bb9adae        800  xla::gpu::(anonymous namespace)::ExecuteThunks()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0bb9c5b0        112  xla::gpu::GpuExecutable::ExecuteThunksOrXlaRuntime()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0bba0e68       2784  xla::gpu::GpuExecutable::ExecuteAsyncOnStreamImpl()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0bba1acf        128  xla::gpu::GpuExecutable::ExecuteAsyncOnStream()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0df86406       1376  xla::Executable::ExecuteAsyncOnStreamWrapper()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad567b0       2432  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad56f20        256  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a3b9c5b0        112  xla::gpu::GpuExecutable::ExecuteThunksOrXlaRuntime()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a3ba0e68       2784  xla::gpu::GpuExecutable::ExecuteAsyncOnStreamImpl()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a3ba1acf        128  xla::gpu::GpuExecutable::ExecuteAsyncOnStream()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a5f86406       1376  xla::Executable::ExecuteAsyncOnStreamWrapper()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d567b0       2432  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d56f20        256  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d1dbca       2720  xla::PjRtStreamExecutorExecutable::EnqueueExecution()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d1f001       5360  xla::PjRtStreamExecutorExecutable::ExecuteHelper()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d21429        240  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d2d848        208  xla::WorkerThread::WorkLoop()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a70e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7fac45626ea5  (unknown)  start_thread
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361: *** SIGSEGV received at time=1671449854 on cpu 64 ***
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361: PC: @     0x7f98a3c03558  (unknown)  xla::gpu::CrossMeshNcclAllReduceThunk::ExecuteOnStream()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7fac4562e630       4016  (unknown)
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a3b9adae        800  xla::gpu::(anonymous namespace)::ExecuteThunks()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a3b9c5b0        112  xla::gpu::GpuExecutable::ExecuteThunksOrXlaRuntime()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a3ba0e68       2784  xla::gpu::GpuExecutable::ExecuteAsyncOnStreamImpl()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a3ba1acf        128  xla::gpu::GpuExecutable::ExecuteAsyncOnStream()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a5f86406       1376  xla::Executable::ExecuteAsyncOnStreamWrapper()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d567b0       2432  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d56f20        256  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d1dbca       2720  xla::PjRtStreamExecutorExecutable::EnqueueExecution()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d1f001       5360  xla::PjRtStreamExecutorExecutable::ExecuteHelper()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d21429        240  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d2d848        208  xla::WorkerThread::WorkLoop()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a70e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7fac45626ea5  (unknown)  start_thread
(MeshHostWorker pid=10617, ip=10.32.10.64) Fatal Python error: Segmentation fault
(MeshHostWorker pid=10617, ip=10.32.10.64)
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad1dbca       2720  xla::PjRtStreamExecutorExecutable::EnqueueExecution()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad1f001       5360  xla::PjRtStreamExecutorExecutable::ExecuteHelper()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad21429        240  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad2d848        208  xla::WorkerThread::WorkLoop()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0f0e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f8dac4e3ea5  (unknown)  start_thread
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361: *** SIGSEGV received at time=1671449853 on cpu 45 ***
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361: PC: @     0x7f7a0bc03558  (unknown)  xla::gpu::CrossMeshNcclAllReduceThunk::ExecuteOnStream()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f8dac4eb630       4016  (unknown)
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0bb9adae        800  xla::gpu::(anonymous namespace)::ExecuteThunks()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0bb9c5b0        112  xla::gpu::GpuExecutable::ExecuteThunksOrXlaRuntime()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0bba0e68       2784  xla::gpu::GpuExecutable::ExecuteAsyncOnStreamImpl()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0bba1acf        128  xla::gpu::GpuExecutable::ExecuteAsyncOnStream()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0df86406       1376  xla::Executable::ExecuteAsyncOnStreamWrapper()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad567b0       2432  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad56f20        256  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad1dbca       2720  xla::PjRtStreamExecutorExecutable::EnqueueExecution()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad1f001       5360  xla::PjRtStreamExecutorExecutable::ExecuteHelper()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad21429        240  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad2d848        208  xla::WorkerThread::WorkLoop()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0f0e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f8dac4e3ea5  (unknown)  start_thread
(MeshHostWorker pid=10615, ip=10.32.10.64) Fatal Python error: Segmentation fault
(MeshHostWorker pid=10615, ip=10.32.10.64)
2022-12-19 19:37:34,561	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff9277d5d9f96d236ba0b09f9904000000 Worker ID: 4f91adc7fd74604526d0af32c0fb472a4a3340f35004167cd41d6c29 Node ID: 3ab6ceca3d8fd41c7ca87a97affe715d04e0aff166fbc0ae885ec012 Worker IP address: 10.32.10.64 Worker port: 10090 Worker PID: 10615 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.


Epoch ... :   0%|          | 0/20 [08:09<?, ?it/s]
Traceback (most recent call last):
  File "run_clm_jax.py", line 832, in <module>
    main()
  File "run_clm_jax.py", line 720, in main
    executable.sync()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 402, in sync
    self.mesh_group.sync_workers()
  File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 2043, in sync_workers
    ray.get([w.sync.remote() for w in all_workers])
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: MeshHostWorker
	actor_id: 9277d5d9f96d236ba0b09f9904000000
	pid: 10615
	namespace: a88d5230-77eb-4105-9d51-3dc734672a7e
	ip: 10.32.10.64
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

---------------------------------------
Job 'raysubmit_S2pZV9iNxPMF5MWS' failed
---------------------------------------
```
