### ISSUE TITLE
Fatal Python error: Segmentation fault

### ISSUE THREAD

**Issue by dumpmemory** [alpa-projects/alpa#819]
**Please describe the bug**
Now for running gpt-neo 125m with [run_clm_flax.py](https://github.com/alpa-projects/alpa/blob/main/examples/gpt2/run_clm_flax.py), it seems that alpa can found a profile setting , but failed after that.

**Please describe the expected behavior**

**System information and environment**
Python version: 3.8
CUDA version: 11.3
NCCL version: 820
cupy version: cupy-cuda113
GPU model and memory: 2080ti 11g
Alpa version: install from source
TensorFlow version: 2.1.0
JAX version: 0.3.22+cuda113.cudnn820

**To Reproduce**
1. run https://github.com/alpa-projects/alpa/blob/main/examples/gpt2/run_clm_flax.py  with  method = alpa.PipeshardParallel(num_micro_batches=training_args.num_micro_batches,
                                       layer_option=alpa.AutoLayerOption(layer_num=2))
2.
3.

```
Profile result saved to: profile-results-2022-12-19-19-36-38.npy
----------------------------------------------------------------------
Result forward_stage_layer_ids: [[0], [1]]
Result mesh_shapes: [(1, 4), (1, 4)]
Result logical_mesh_shapes: [(4, 1), (4, 1)]
Result autosharding_option_dicts: [{'force_batch_dim_to_mesh_dim': 0}, {}]
2022-12-19 19:37:04,734	WARNING worker.py:1851 -- It looks like you're creating a detached actor in an anonymous namespace. In order to access this actor in the future, you will need to explicitly connect to this namespace with ray.init(namespace="a88d5230-77eb-4105-9d51-3dc734672a7e", ...)
(MeshHostWorker pid=10617, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f98a3c03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10617, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f98a3c03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10617, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f98a3c03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10617, ip=10.32.10.64) *** SIGSEGV received at time=1671449853 on cpu 64 ***
(MeshHostWorker pid=10617, ip=10.32.10.64) PC: @     0x7f98a3c03558  (unknown)  xla::gpu::CrossMeshNcclAllReduceThunk::ExecuteOnStream()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7fac4562e630       4016  (unknown)
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a3b9adae        800  xla::gpu::(anonymous namespace)::ExecuteThunks()
(MeshHostWorker pid=10615, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f7a0bc03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10615, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f7a0bc03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10615, ip=10.32.10.64) [failure_signal_handler.cc : 331] RAW: Signal 11 raised at PC=0x7f7a0bc03558 while already in AbslFailureSignalHandler()
(MeshHostWorker pid=10615, ip=10.32.10.64) *** SIGSEGV received at time=1671449853 on cpu 45 ***
(MeshHostWorker pid=10615, ip=10.32.10.64) PC: @     0x7f7a0bc03558  (unknown)  xla::gpu::CrossMeshNcclAllReduceThunk::ExecuteOnStream()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f8dac4eb630       4016  (unknown)
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0bb9adae        800  xla::gpu::(anonymous namespace)::ExecuteThunks()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0bb9c5b0        112  xla::gpu::GpuExecutable::ExecuteThunksOrXlaRuntime()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0bba0e68       2784  xla::gpu::GpuExecutable::ExecuteAsyncOnStreamImpl()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0bba1acf        128  xla::gpu::GpuExecutable::ExecuteAsyncOnStream()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0df86406       1376  xla::Executable::ExecuteAsyncOnStreamWrapper()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad567b0       2432  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad56f20        256  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a3b9c5b0        112  xla::gpu::GpuExecutable::ExecuteThunksOrXlaRuntime()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a3ba0e68       2784  xla::gpu::GpuExecutable::ExecuteAsyncOnStreamImpl()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a3ba1acf        128  xla::gpu::GpuExecutable::ExecuteAsyncOnStream()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a5f86406       1376  xla::Executable::ExecuteAsyncOnStreamWrapper()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d567b0       2432  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d56f20        256  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d1dbca       2720  xla::PjRtStreamExecutorExecutable::EnqueueExecution()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d1f001       5360  xla::PjRtStreamExecutorExecutable::ExecuteHelper()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d21429        240  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a2d2d848        208  xla::WorkerThread::WorkLoop()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7f98a70e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=10617, ip=10.32.10.64)     @     0x7fac45626ea5  (unknown)  start_thread
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361: *** SIGSEGV received at time=1671449854 on cpu 64 ***
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361: PC: @     0x7f98a3c03558  (unknown)  xla::gpu::CrossMeshNcclAllReduceThunk::ExecuteOnStream()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7fac4562e630       4016  (unknown)
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a3b9adae        800  xla::gpu::(anonymous namespace)::ExecuteThunks()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a3b9c5b0        112  xla::gpu::GpuExecutable::ExecuteThunksOrXlaRuntime()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a3ba0e68       2784  xla::gpu::GpuExecutable::ExecuteAsyncOnStreamImpl()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a3ba1acf        128  xla::gpu::GpuExecutable::ExecuteAsyncOnStream()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a5f86406       1376  xla::Executable::ExecuteAsyncOnStreamWrapper()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d567b0       2432  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d56f20        256  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d1dbca       2720  xla::PjRtStreamExecutorExecutable::EnqueueExecution()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d1f001       5360  xla::PjRtStreamExecutorExecutable::ExecuteHelper()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d21429        240  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a2d2d848        208  xla::WorkerThread::WorkLoop()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7f98a70e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=10617, ip=10.32.10.64) [2022-12-19 19:37:34,025 E 10617 10781] logging.cc:361:     @     0x7fac45626ea5  (unknown)  start_thread
(MeshHostWorker pid=10617, ip=10.32.10.64) Fatal Python error: Segmentation fault
(MeshHostWorker pid=10617, ip=10.32.10.64)
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad1dbca       2720  xla::PjRtStreamExecutorExecutable::EnqueueExecution()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad1f001       5360  xla::PjRtStreamExecutorExecutable::ExecuteHelper()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad21429        240  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0ad2d848        208  xla::WorkerThread::WorkLoop()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f7a0f0e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=10615, ip=10.32.10.64)     @     0x7f8dac4e3ea5  (unknown)  start_thread
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361: *** SIGSEGV received at time=1671449853 on cpu 45 ***
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361: PC: @     0x7f7a0bc03558  (unknown)  xla::gpu::CrossMeshNcclAllReduceThunk::ExecuteOnStream()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f8dac4eb630       4016  (unknown)
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0bb9adae        800  xla::gpu::(anonymous namespace)::ExecuteThunks()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0bb9c5b0        112  xla::gpu::GpuExecutable::ExecuteThunksOrXlaRuntime()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0bba0e68       2784  xla::gpu::GpuExecutable::ExecuteAsyncOnStreamImpl()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0bba1acf        128  xla::gpu::GpuExecutable::ExecuteAsyncOnStream()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0df86406       1376  xla::Executable::ExecuteAsyncOnStreamWrapper()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad567b0       2432  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad56f20        256  xla::LocalExecutable::RunAsync()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad1dbca       2720  xla::PjRtStreamExecutorExecutable::EnqueueExecution()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad1f001       5360  xla::PjRtStreamExecutorExecutable::ExecuteHelper()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad21429        240  std::_Function_handler<>::_M_invoke()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0ad2d848        208  xla::WorkerThread::WorkLoop()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f7a0f0e1105         80  tsl::(anonymous namespace)::PThread::ThreadFn()
(MeshHostWorker pid=10615, ip=10.32.10.64) [2022-12-19 19:37:33,991 E 10615 10885] logging.cc:361:     @     0x7f8dac4e3ea5  (unknown)  start_thread
(MeshHostWorker pid=10615, ip=10.32.10.64) Fatal Python error: Segmentation fault
(MeshHostWorker pid=10615, ip=10.32.10.64)
2022-12-19 19:37:34,561	WARNING worker.py:1851 -- A worker died or was killed while executing a task by an unexpected system error. To troubleshoot the problem, check the logs for the dead worker. RayTask ID: ffffffffffffffff9277d5d9f96d236ba0b09f9904000000 Worker ID: 4f91adc7fd74604526d0af32c0fb472a4a3340f35004167cd41d6c29 Node ID: 3ab6ceca3d8fd41c7ca87a97affe715d04e0aff166fbc0ae885ec012 Worker IP address: 10.32.10.64 Worker port: 10090 Worker PID: 10615 Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.


Epoch ... :   0%|          | 0/20 [08:09<?, ?it/s]
Traceback (most recent call last):
  File "run_clm_jax.py", line 832, in <module>
    main()
  File "run_clm_jax.py", line 720, in main
    executable.sync()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 402, in sync
    self.mesh_group.sync_workers()
  File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 2043, in sync_workers
    ray.get([w.sync.remote() for w in all_workers])
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/worker.py", line 2311, in get
    raise value
ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
	class_name: MeshHostWorker
	actor_id: 9277d5d9f96d236ba0b09f9904000000
	pid: 10615
	namespace: a88d5230-77eb-4105-9d51-3dc734672a7e
	ip: 10.32.10.64
The actor is dead because its worker process has died. Worker exit type: SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. (1) The process is killed by SIGKILL by OOM killer due to high memory usage. (2) ray stop --force is called. (3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.

---------------------------------------
Job 'raysubmit_S2pZV9iNxPMF5MWS' failed
```
**Screenshots**

**Code snippet to reproduce the problem**

**Additional information**
Add any other context about the problem here or include any logs that would be helpful to diagnose the problem.

**Comment by dumpmemory** [comment]
with original method = alpa.Zero2Parallel(num_micro_batches=training_args.num_micro_batches), it can work smoothly.  But when i use PipeshardParallel it doesn't work anymore.

**Comment by dumpmemory** [comment]
I can run https://github.com/alpa-projects/alpa/blob/main/examples/opt_finetune/run_2.7b_shard.sh now. I have change the main function into ray.remote and it worked. I will test PipeshardParallel again

**Comment by dumpmemory** [comment]
I can't running https://github.com/alpa-projects/alpa/blob/main/examples/opt_finetune/run_2.7b_shard.sh with gpt-neo 1.3b, i have removed deterministic args. using following command 
```
 ray job submit --working-dir . --address http://10.32.10.198:8265/ --  python3 run_clm_flax_opt.py     --output_dir="/mnt/train/test_gpt-neo-1.3b"     --model_name_or_path="EleutherAI/gpt-neo-1.3B"     --dataset_name="wikitext"     --dataset_config_name="wikitext-2-raw-v1"     --do_train --do_eval     --block_size="1024"     --per_device_train_batch_size="2"     --per_device_eval_batch_size="2"     --num_micro_batches 2     --operator_parallel 2     --pipeline_parallel 4     --dtype="float16"     --learning_rate="5e-4" --warmup_steps="2000"     --adam_beta1="0.9" --adam_beta2="0.98" --weight_decay="0.01"     --overwrite_output_dir     --num_train_epochs="8"     --logging_steps="16"     --save_steps="2500"     --eval_steps="2500"
```
Error log
```
(main pid=37087, ip=10.32.13.122) INFO:__main__:***** Running training *****
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Num examples = 2318
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Num Epochs = 8
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Batch size per device (w. accumulation) = 2
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Global train batch size (w. parallel & distributed) = 16
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Total optimization steps = 1152
(main pid=37087, ip=10.32.13.122)
Epoch ... :   0%|          | 0/8 [00:00<?, ?it/s]


Epoch ... :   0%|          | 0/8 [00:00<?, ?it/s]
(main pid=37087, ip=10.32.13.122)
(main pid=37087, ip=10.32.13.122) Initial compilation. This might take some minutes...
Traceback (most recent call last):
  File "run_clm_flax_opt.py", line 1039, in <module>
    ray.get(main.remote(model_args,data_args,training_args))
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::main() (pid=37087, ip=10.32.13.122)
  File "run_clm_flax_opt.py", line 900, in main
    state, train_metric = p_train_step(state, batch)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/nlp/HF/alpa/alpa/api.py", line 121, in __call__
    self._decode_args_and_get_executable(*args))
  File "/home/nlp/HF/alpa/alpa/api.py", line 191, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/home/nlp/miniconda/lib/python3.8/site-packages/jax/linear_util.py", line 309, in memoized_fun
    ans = call(fun, *args)
  File "/home/nlp/HF/alpa/alpa/api.py", line 223, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/home/nlp/HF/alpa/alpa/parallel_method.py", line 233, in compile_executable
    return compile_pipeshard_executable(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 95, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 261, in compile_pipeshard_executable_internal
    pipeshard_config = emitter_cls(**emitter_kwargs).compile()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/runtime_emitter.py", line 391, in compile
    self._compile_resharding_tasks()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/runtime_emitter.py", line 330, in _compile_resharding_tasks
    var] = SymbolicReshardingTask(spec, cg, src_mesh,
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 199, in __init__
    self._compile()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 224, in _compile
    self.put_all_tasks()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 244, in put_all_tasks
    ray.get(task_dones)
jax._src.traceback_util.UnfilteredStackTrace: ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=38428, ip=10.32.13.122, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f0b16f9b1c0>)
  File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 127, in __init__
    self.distributed_client.connect()
jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: ABORTED: Connect() called when system is not initializing.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ray::main() (pid=37087, ip=10.32.13.122)
  File "run_clm_flax_opt.py", line 900, in main
    state, train_metric = p_train_step(state, batch)
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 95, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 261, in compile_pipeshard_executable_internal
    pipeshard_config = emitter_cls(**emitter_kwargs).compile()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/runtime_emitter.py", line 391, in compile
    self._compile_resharding_tasks()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/runtime_emitter.py", line 330, in _compile_resharding_tasks
    var] = SymbolicReshardingTask(spec, cg, src_mesh,
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 199, in __init__
    self._compile()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 224, in _compile
    self.put_all_tasks()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 244, in put_all_tasks
    ray.get(task_dones)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=38428, ip=10.32.13.122, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f0b16f9b1c0>)
  File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 127, in __init__
    self.distributed_client.connect()
jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: ABORTED: Connect() called when system is not initializing.
(main pid=37087, ip=10.32.13.122)
(main pid=37087, ip=10.32.13.122)
Epoch ... :   0%|          | 0/8 [00:54<?, ?it/s]
(MeshHostWorker pid=38428, ip=10.32.13.122) 2022-12-21 15:40:47.329889: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:218] Connect() failed after 1 retries in 0; most recent failure status: ABORTED: Connect() called when system is not initializing.
(MeshHostWorker pid=38428, ip=10.32.13.122) 2022-12-21 15:40:47,331	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=38428, ip=10.32.13.122, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f0b16f9b1c0>)
(MeshHostWorker pid=38428, ip=10.32.13.122)   File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 127, in __init__
(MeshHostWorker pid=38428, ip=10.32.13.122)     self.distributed_client.connect()
(MeshHostWorker pid=38428, ip=10.32.13.122) jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: ABORTED: Connect() called when system is not initializing.
(MeshHostWorker pid=38429, ip=10.32.13.122) 2022-12-21 15:40:47.407148: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:218] Connect() failed after 1 retries in 0; most recent failure status: ABORTED: Connect() called when system is not initializing.
(MeshHostWorker pid=38429, ip=10.32.13.122) 2022-12-21 15:40:47,408	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=38429, ip=10.32.13.122, repr=<alpa.device_mesh.MeshHostWorker object at 0x7fa0e1f0d1f0>)
(MeshHostWorker pid=38429, ip=10.32.13.122)   File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 127, in __init__
(MeshHostWorker pid=38429, ip=10.32.13.122)     self.distributed_client.connect()
(MeshHostWorker pid=38429, ip=10.32.13.122) jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: ABORTED: Connect() called when system is not initializing.
```
