### ISSUE TITLE
jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. 

### ISSUE THREAD

**Issue by dumpmemory** [alpa-projects/alpa#826]
**Please describe the bug**

I can't running https://github.com/dumpmemory/alpa/blob/49818ad85da01a52f86e3c2b92e9681d991c4639/examples/opt_finetune/test_run_clm_flax_opt.py with gpt-neo 1.3b, i have removed deterministic args. using following command

ray version is 2.2.0
```
 ray job submit --working-dir . --address http://10.32.10.198:8265/ --  python3 run_clm_flax_opt.py     --output_dir="/mnt/train/test_gpt-neo-1.3b"     --model_name_or_path="EleutherAI/gpt-neo-1.3B"     --dataset_name="wikitext"     --dataset_config_name="wikitext-2-raw-v1"     --do_train --do_eval     --block_size="1024"     --per_device_train_batch_size="2"     --per_device_eval_batch_size="2"     --num_micro_batches 2     --operator_parallel 2     --pipeline_parallel 4     --dtype="float16"     --learning_rate="5e-4" --warmup_steps="2000"     --adam_beta1="0.9" --adam_beta2="0.98" --weight_decay="0.01"     --overwrite_output_dir     --num_train_epochs="8"     --logging_steps="16"     --save_steps="2500"     --eval_steps="2500"
```

**Please describe the expected behavior**

System information and environment
Python version: 3.8
CUDA version: 11.3
NCCL version: 820
cupy version: cupy-cuda113
GPU model and memory: 2080ti 11g
Alpa version: install from source
TensorFlow version: 2.1.0
JAX version: 0.3.22+cuda113.cudnn820

**To Reproduce**
1.
2.
3.
Error log
```
(main pid=37087, ip=10.32.13.122) INFO:__main__:***** Running training *****
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Num examples = 2318
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Num Epochs = 8
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Batch size per device (w. accumulation) = 2
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Global train batch size (w. parallel & distributed) = 16
(main pid=37087, ip=10.32.13.122) INFO:__main__:  Total optimization steps = 1152
(main pid=37087, ip=10.32.13.122)
Epoch ... :   0%|          | 0/8 [00:00<?, ?it/s]


Epoch ... :   0%|          | 0/8 [00:00<?, ?it/s]
(main pid=37087, ip=10.32.13.122)
(main pid=37087, ip=10.32.13.122) Initial compilation. This might take some minutes...
Traceback (most recent call last):
  File "run_clm_flax_opt.py", line 1039, in <module>
    ray.get(main.remote(model_args,data_args,training_args))
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/ray/_private/worker.py", line 2309, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError: ray::main() (pid=37087, ip=10.32.13.122)
  File "run_clm_flax_opt.py", line 900, in main
    state, train_metric = p_train_step(state, batch)
  File "/home/nlp/miniconda/lib/python3.8/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/nlp/HF/alpa/alpa/api.py", line 121, in __call__
    self._decode_args_and_get_executable(*args))
  File "/home/nlp/HF/alpa/alpa/api.py", line 191, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/home/nlp/miniconda/lib/python3.8/site-packages/jax/linear_util.py", line 309, in memoized_fun
    ans = call(fun, *args)
  File "/home/nlp/HF/alpa/alpa/api.py", line 223, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/home/nlp/HF/alpa/alpa/parallel_method.py", line 233, in compile_executable
    return compile_pipeshard_executable(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 95, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 261, in compile_pipeshard_executable_internal
    pipeshard_config = emitter_cls(**emitter_kwargs).compile()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/runtime_emitter.py", line 391, in compile
    self._compile_resharding_tasks()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/runtime_emitter.py", line 330, in _compile_resharding_tasks
    var] = SymbolicReshardingTask(spec, cg, src_mesh,
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 199, in __init__
    self._compile()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 224, in _compile
    self.put_all_tasks()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 244, in put_all_tasks
    ray.get(task_dones)
jax._src.traceback_util.UnfilteredStackTrace: ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=38428, ip=10.32.13.122, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f0b16f9b1c0>)
  File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 127, in __init__
    self.distributed_client.connect()
jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: ABORTED: Connect() called when system is not initializing.

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

ray::main() (pid=37087, ip=10.32.13.122)
  File "run_clm_flax_opt.py", line 900, in main
    state, train_metric = p_train_step(state, batch)
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 95, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/compile_executable.py", line 261, in compile_pipeshard_executable_internal
    pipeshard_config = emitter_cls(**emitter_kwargs).compile()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/runtime_emitter.py", line 391, in compile
    self._compile_resharding_tasks()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/runtime_emitter.py", line 330, in _compile_resharding_tasks
    var] = SymbolicReshardingTask(spec, cg, src_mesh,
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 199, in __init__
    self._compile()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 224, in _compile
    self.put_all_tasks()
  File "/home/nlp/HF/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 244, in put_all_tasks
    ray.get(task_dones)
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=38428, ip=10.32.13.122, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f0b16f9b1c0>)
  File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 127, in __init__
    self.distributed_client.connect()
jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: ABORTED: Connect() called when system is not initializing.
(main pid=37087, ip=10.32.13.122)
(main pid=37087, ip=10.32.13.122)
Epoch ... :   0%|          | 0/8 [00:54<?, ?it/s]
(MeshHostWorker pid=38428, ip=10.32.13.122) 2022-12-21 15:40:47.329889: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:218] Connect() failed after 1 retries in 0; most recent failure status: ABORTED: Connect() called when system is not initializing.
(MeshHostWorker pid=38428, ip=10.32.13.122) 2022-12-21 15:40:47,331	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=38428, ip=10.32.13.122, repr=<alpa.device_mesh.MeshHostWorker object at 0x7f0b16f9b1c0>)
(MeshHostWorker pid=38428, ip=10.32.13.122)   File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 127, in __init__
(MeshHostWorker pid=38428, ip=10.32.13.122)     self.distributed_client.connect()
(MeshHostWorker pid=38428, ip=10.32.13.122) jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: ABORTED: Connect() called when system is not initializing.
(MeshHostWorker pid=38429, ip=10.32.13.122) 2022-12-21 15:40:47.407148: E external/org_tensorflow/tensorflow/compiler/xla/pjrt/distributed/client.cc:218] Connect() failed after 1 retries in 0; most recent failure status: ABORTED: Connect() called when system is not initializing.
(MeshHostWorker pid=38429, ip=10.32.13.122) 2022-12-21 15:40:47,408	ERROR worker.py:763 -- Exception raised in creation task: The actor died because of an error raised in its creation task, ray::MeshHostWorker.__init__() (pid=38429, ip=10.32.13.122, repr=<alpa.device_mesh.MeshHostWorker object at 0x7fa0e1f0d1f0>)
(MeshHostWorker pid=38429, ip=10.32.13.122)   File "/home/nlp/HF/alpa/alpa/device_mesh.py", line 127, in __init__
(MeshHostWorker pid=38429, ip=10.32.13.122)     self.distributed_client.connect()
(MeshHostWorker pid=38429, ip=10.32.13.122) jaxlib.xla_extension.XlaRuntimeError: DEADLINE_EXCEEDED: Connect() timed out after 0 with 1 attempts. Most recent failure was: ABORTED: Connect() called when system is not initializing.
```

**Screenshots**

**Code snippet to reproduce the problem**

**Additional information**
But Following two ray job command worked.  the main difference is --operator_parallel 4     --pipeline_parallel 1
```
ray job submit --runtime-env-json='{"env_vars": {"HF_DATASETS_CACHE":"/mnt/train/huggingface_cache","TRANSFORMERS_CACHE":"/mnt/train/huggingface_cache/hub","TOKENIZERS_PARALLELISM":"false"}}' --working-dir . --address http://10.32.10.198:8265/ --  python3 run_clm_flax_opt.py     --output_dir="/mnt/train/test_opt"     --model_name_or_path="EleutherAI/gpt-neo-1.3B"     --dataset_name="wikitext"     --dataset_config_name="wikitext-2-raw-v1"     --do_train --do_eval     --block_size="512"     --per_device_train_batch_size="2"     --per_device_eval_batch_size="2"     --num_micro_batches 2     --operator_parallel 4     --pipeline_parallel 1    --dtype="float32"     --learning_rate="5e-4" --warmup_steps="2000"     --adam_beta1="0.9" --adam_beta2="0.98" --weight_decay="0.01"     --overwrite_output_dir     --num_train_epochs="8"     --logging_steps="16"     --save_steps="2500"     --eval_steps="2500"

ray job submit --runtime-env-json='{"env_vars": {"HF_DATASETS_CACHE":"/mnt/train/huggingface_cache","TRANSFORMERS_CACHE":"/mnt/train/huggingface_cache/hub","TOKENIZERS_PARALLELISM":"false"}}' --working-dir . --address http://10.32.10.198:8265/ --  python3 run_clm_flax_opt.py     --output_dir="/mnt/train/test_opt"     --model_name_or_path="EleutherAI/gpt-neo-1.3B"     --dataset_name="wikitext"     --dataset_config_name="wikitext-2-raw-v1"     --do_train --do_eval     --block_size="512"     --per_device_train_batch_size="2"     --per_device_eval_batch_size="2"     --num_micro_batches 2     --operator_parallel 4     --pipeline_parallel 1    --dtype="float16"     --learning_rate="5e-4" --warmup_steps="2000"     --adam_beta1="0.9" --adam_beta2="0.98" --weight_decay="0.01"     --overwrite_output_dir     --num_train_epochs="8"     --logging_steps="16"     --save_steps="2500"     --eval_steps="2500"
```

Is there any instruction for setting args to avoid this kind error

**Comment by dumpmemory** [comment]
This might be from my docker port connection issue . I will check it. Thanks
