### ISSUE TITLE
[BUG] numpy.int Deprecated in 1.20 and removed in 1.24

### ISSUE THREAD

**Issue by EntilZha** [alpa-projects/alpa#836]
**Please describe the bug**

If using `numpy>=1.24`, `np.int` is undefined, causing this error:

```
Traceback (most recent call last):                                                                                                                                                             
  File "/private/home/par/code/hcir/lm-jax/retro_main.py", line 136, in main                                                                                                                   
    train.train_and_evaluate(cfg)                                                                                                                                                              
  File "/private/home/par/code/hcir/lm-jax/retro/train.py", line 443, in train_and_evaluate                                                                                                    
    import alpa                                                                                                                                                                                
  File "/private/home/par/miniconda3/envs/alpa/lib/python3.9/site-packages/alpa/__init__.py", line 3, in <module>                                                                              
    from . import api                                                                                                                                                                          
  File "/private/home/par/miniconda3/envs/alpa/lib/python3.9/site-packages/alpa/api.py", line 13, in <module>                                                                                  
    from alpa.device_mesh import init_global_cluster, shutdown_global_cluster                                                                                                                  
  File "/private/home/par/miniconda3/envs/alpa/lib/python3.9/site-packages/alpa/device_mesh.py", line 49, in <module>                                                                          
    import alpa.collective as col                                                                                                                                                              
  File "/private/home/par/miniconda3/envs/alpa/lib/python3.9/site-packages/alpa/collective/__init__.py", line 3, in <module>                                                                   
    from alpa.collective.collective import (                                                                                                                                                   
  File "/private/home/par/miniconda3/envs/alpa/lib/python3.9/site-packages/alpa/collective/collective.py", line 23, in <module>                                                                
    from alpa.collective.collective_group.nccl_collective_group import (                                                                                                                       
  File "/private/home/par/miniconda3/envs/alpa/lib/python3.9/site-packages/alpa/collective/collective_group/nccl_collective_group.py", line 9, in <module>                                     
    from alpa.collective.collective_group import nccl_util                                                                                                                                     
  File "/private/home/par/miniconda3/envs/alpa/lib/python3.9/site-packages/alpa/collective/collective_group/nccl_util.py", line 32, in <module>                                                
    numpy.int: nccl.NCCL_INT64,                                                                                                                                                                
  File "/private/home/par/miniconda3/envs/alpa/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__                                                                        
    raise AttributeError("module {!r} has no attribute "                                                                                                                                       
AttributeError: module 'numpy' has no attribute 'int' 
```

The `np.int` used here https://github.com/alpa-projects/alpa/blob/v0.2.2/alpa/collective/collective_group/nccl_util.py#L32 was deprecated in 1.20 and removed in 1.24 (https://github.com/numpy/numpy/releases/tag/v1.24.0), causing the error.

The quick fix is to require `numpy<1.24`, but probably the best thing I'm guessing is to modify the file above to use `numpy.int64`

**Comment by zhisbug** [comment]
@EntilZha thanks for the issue. We'll fix it.

**Comment by sammeralomair** [comment]
working on this

**Comment by sammeralomair** [comment]
made PR for it https://github.com/alpa-projects/alpa/pull/921
