### ISSUE TITLE
AssertionError when using PipeshardParallel for inference

### ISSUE THREAD

**Issue by leiteg** [alpa-projects/alpa#875]
# Problem

Hello, I am trying to use `PipeshardParallel` method with ResNet18 model in a cluster using two nodes. However, when the `model.apply` function is invoked, Alpa triggers an assertion error inside the function `slice_closed_jaxpr_by_full_pipeline_marks`. Here is the full log with stack trace. I am not sure if I am using the API wrong or if this is indeed a bug, but I am assuming a bug since it is an assertion error

```python
WARNING:alpa.pipeline_parallel.apply_grad:Missing microbatch_bound between compute and apply. Assume there is no apply gradient step. Hint: replace jax.grad by alpa.grad.
Traceback (most recent call last):
  File "main_simple.py", line 40, in <module>
    result, mutated_vars = apply(params, x)
  File "/usr/local/lib/python3.8/dist-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/alpa/api.py", line 121, in __call__
    self._decode_args_and_get_executable(*args))
  File "/usr/local/lib/python3.8/dist-packages/alpa/api.py", line 191, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/usr/local/lib/python3.8/dist-packages/jax/linear_util.py", line 309, in memoized_fun
    ans = call(fun, *args)
  File "/usr/local/lib/python3.8/dist-packages/alpa/api.py", line 218, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/usr/local/lib/python3.8/dist-packages/alpa/parallel_method.py", line 233, in compile_executable
    return compile_pipeshard_executable(
  File "/usr/local/lib/python3.8/dist-packages/alpa/pipeline_parallel/compile_executable.py", line 93, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/usr/local/lib/python3.8/dist-packages/alpa/pipeline_parallel/compile_executable.py", line 158, in compile_pipeshard_executable_internal
    jax_pipeline_layers = slice_closed_jaxpr_by_full_pipeline_marks(
  File "/usr/local/lib/python3.8/dist-packages/alpa/pipeline_parallel/computation.py", line 395, in slice_closed_jaxpr_by_full_pipeline_marks
    assert current_computation is not None
jax._src.traceback_util.UnfilteredStackTrace: AssertionError

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main_simple.py", line 40, in <module>
    result, mutated_vars = apply(params, x)
  File "/usr/local/lib/python3.8/dist-packages/alpa/pipeline_parallel/compile_executable.py", line 93, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/usr/local/lib/python3.8/dist-packages/alpa/pipeline_parallel/compile_executable.py", line 158, in compile_pipeshard_executable_internal
    jax_pipeline_layers = slice_closed_jaxpr_by_full_pipeline_marks(
  File "/usr/local/lib/python3.8/dist-packages/alpa/pipeline_parallel/computation.py", line 395, in slice_closed_jaxpr_by_full_pipeline_marks
    assert current_computation is not None
AssertionError
```

# Source Code

Here is the code I used to reproduce this bug. The `ResNet18` model  used is identical to the one found in the [Alpa examples](https://github.com/alpa-projects/alpa/blob/main/examples/imagenet/models.py).

```python
import jax
import alpa
import models
import numpy as np

import jax.numpy as jnp

# Alpa Initialization
# ==============================================================================

alpa.init(cluster="ray")

# Data Initialization
# ==============================================================================

dim = 4096
batch_size = 32
num_classes = 128

k0 = jax.random.PRNGKey(0)
k0, k1 = jax.random.split(k0)
k0, k2 = jax.random.split(k0)
k0, k3 = jax.random.split(k0)

x = jax.random.normal(k1, (batch_size, dim, dim, 3))

# Model Initialization
# ==============================================================================

model = models.ResNet18(num_classes=num_classes, dtype=jnp.float32)
params = model.init(k3, x)

@alpa.parallelize(method=alpa.PipeshardParallel())
def apply(*args):
  return model.apply(*args, mutable=["batch_stats"])

# Feed forward
# ==============================================================================

result, mutated_vars = apply(params, x)

print(result.shape)
print(result)
```
# Reproducing

I am running this code on Slurm, and my sbatch script is given below. I have reproduced this bug using both Python virtualenvs and a Singularity (Apptainer) container image. The command to run is: `sbatch -A <account> -p <partition> run.sh`.

```bash
#!/usr/bin/env bash

#SBATCH --job-name=alpa
#SBATCH --nodes=2
#SBATCH --tasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=1GB
#SBATCH --time=00:30:00

module purge
module load python/3.9.6
module load cuda/11.5
module list

source venv/bin/activate

which python python3 pip pip3
pip list

# RAY INIT
# ------------------------------------------------------------------------------

# Get names of nodes assigned
nodes=$(scontrol show hostnames "$SLURM_JOB_NODELIST")
nodes_array=($nodes)

# By default, set the first node to be head_node on which we run HEAD of Ray
head_node=${nodes_array[0]}
head_node_ip=$(srun --nodes=1 --ntasks=1 -w "$head_node" hostname --ip-address)

# Setup port and variables needed
gpus_per_node=4
port=6789
ip_head=$head_node_ip:$port
export ip_head
# Start HEAD in background of head node
srun --nodes=1 --ntasks=1 -w "$head_node" \
        ray start --head --node-ip-address="$head_node_ip" --port=$port \
        --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus $gpus_per_node --block &

# Start worker nodes
# Number of nodes other than the head node
worker_num=$((SLURM_JOB_NUM_NODES - 1))
# Iterate on each node other than head node, start ray worker and connect to HEAD
for ((i = 1; i <= worker_num; i++)); do
    node_i=${nodes_array[$i]}
    echo "==> Starting WORKER $i at $node_i"
    srun --nodes=1 --ntasks=1 -w "$node_i" \
        ray start --address "$ip_head" --num-cpus "${SLURM_CPUS_PER_TASK}" \
        --num-gpus $gpus_per_node --block &
    sleep 5
done

# USER CODE
# ------------------------------------------------------------------------------

python3 main.py

# RAY STOP
# ------------------------------------------------------------------------------

ray stop
```

# System Information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker):
- Python version: 3.9.6
- CUDA version: 11.5
- NCCL version: 2.7.8
- cupy version: 11.5.0
- GPU model and memory: Two cluster nodes with 4x NVIDIA-V100-PCIE-32GB each.
- Alpa version: 0.2.2
- TensorFlow version: None
- JAX version: 0.3.22

I am willing to provide further information if needed. Thanks in advance!

**Comment by samblouir** [comment]
Similar issue here. I'm using Slurm, too. Even a single 1-layer layer MLP network seems to re-create this. ShardParallel, Zero2, and Zero3 are able to start training on the same code.

**Comment by merrymercy** [comment]
If it is inference only, please see examples here https://github.com/alpa-projects/alpa/blob/66a77da2fa4dfc15dcc0045976dcb64537c88512/tests/pipeline_parallel/test_inference_only.py#L88.

You should use a slightly different option

**Comment by leiteg** [comment]
Thanks @merrymercy, the original problem indeed went away. Now, however, I get a timeout error. Do you have any idea what might be causing this? It seems to be more related to Ray. I can move this discussion to a new issue if you prefer.

```python
[2m[1m[36m(scheduler +9m24s)[0m Tip: use `ray status` to view detailed cluster status. To disable these messages, set RAY_SCHEDULER_EVENTS=0.
[2m[1m[33m(scheduler +9m24s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +9m59s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +10m34s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +11m9s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +11m44s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +12m19s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +12m54s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +13m29s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +14m5s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +14m40s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +15m15s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +15m50s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +16m25s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +17m0s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
[2m[1m[33m(scheduler +17m35s)[0m Warning: The following resource request cannot be scheduled right now: {'CPU': 1.0}. This is likely due to all cluster resources being claimed by actors. Consider creating fewer actors or adding more nodes to this Ray cluster.
Traceback (most recent call last):
  File "/home/gustavo.leite/alpa/examples/conda/main.py", line 81, in <module>
    result, mutated_vars = apply(x)
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/jax/_src/traceback_util.py", line 162, in reraise_with_filtered_traceback
    return fun(*args, **kwargs)
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/api.py", line 121, in __call__
    self._decode_args_and_get_executable(*args))
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/api.py", line 191, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/jax/linear_util.py", line 309, in memoized_fun
    ans = call(fun, *args)
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/api.py", line 218, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/parallel_method.py", line 233, in compile_executable
    return compile_pipeshard_executable(
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/compile_executable.py", line 93, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/compile_executable.py", line 237, in compile_pipeshard_executable_internal
    xla_stages, total_flops = shard_each_stage(
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/compile_executable.py", line 361, in shard_each_stage
    stage_plan) = compile_workers.get_next_unordered()
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/stage_profiling.py", line 85, in get_next_unordered
    return self.pool.get_next_unordered(
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/util/actor_pool.py", line 254, in get_next_unordered
    raise TimeoutError(timeout_msg)
jax._src.traceback_util.UnfilteredStackTrace: TimeoutError: Timed out waiting for result

The stack trace below excludes JAX-internal frames.
The preceding is the original exception that occurred, unmodified.

--------------------

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gustavo.leite/alpa/examples/conda/main.py", line 81, in <module>
    result, mutated_vars = apply(x)
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/compile_executable.py", line 93, in compile_pipeshard_executable
    pipeshard_config = compile_pipeshard_executable_internal(
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/compile_executable.py", line 237, in compile_pipeshard_executable_internal
    xla_stages, total_flops = shard_each_stage(
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/compile_executable.py", line 361, in shard_each_stage
    stage_plan) = compile_workers.get_next_unordered()
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/stage_profiling.py", line 85, in get_next_unordered
    return self.pool.get_next_unordered(
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/util/actor_pool.py", line 254, in get_next_unordered
    raise TimeoutError(timeout_msg)
TimeoutError: Timed out waiting for result
2023-02-13 11:49:46,879	ERROR services.py:1403 -- Failed to start the dashboard: 'NoneType' object is not iterable
2023-02-13 11:49:46,879	ERROR services.py:1404 -- 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/services.py", line 1288, in start_api_server
    minimal = not ray._private.utils.check_dashboard_dependencies_installed()
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/utils.py", line 1291, in check_dashboard_dependencies_installed
    import ray.dashboard.optional_deps  # noqa: F401
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/dashboard/optional_deps.py", line 8, in <module>
    import opencensus  # noqa: F401
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1380, in _get_spec
TypeError: 'NoneType' object is not iterable
Exception ignored in: <function BaseWorkerPoolWrapper.__del__ at 0x7f62c954d670>
Traceback (most recent call last):
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/stage_profiling.py", line 100, in __del__
    self.shutdown()
  File "/home/gustavo.leite/alpa/examples/conda/alpa/alpa/pipeline_parallel/stage_profiling.py", line 92, in shutdown
    ray.kill(w)
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 100, in wrapper
    if client_mode_should_convert(auto_init=auto_init):
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 124, in client_mode_should_convert
    ray.init()
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/worker.py", line 1429, in init
    _global_node = ray._private.node.Node(
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/node.py", line 309, in __init__
    self.start_ray_processes()
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/node.py", line 1112, in start_ray_processes
    resource_spec = self.get_resource_spec()
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/node.py", line 471, in get_resource_spec
    self._resource_spec = ResourceSpec(
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/resource_spec.py", line 175, in resolve
    num_gpus = _autodetect_num_gpus()
  File "/home/gustavo.leite/alpa/examples/conda/venv/lib/python3.9/site-packages/ray/_private/resource_spec.py", line 277, in _autodetect_num_gpus
    if importlib.util.find_spec("GPUtil"):
  File "/opt/share/python/3.9.6/lib/python3.9/importlib/util.py", line 103, in find_spec
    return _find_spec(fullname, parent_path)
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1380, in _get_spec
TypeError: 'NoneType' object is not iterable

```

**Comment by samblouir** [comment]
When the program is stuck waiting, what does running "ray status" show? Does it see your GPUs? It looks like the profiling is trying to create more processes via Ray than the amount of available logical CPUs on your machine.

**Comment by leiteg** [comment]
@samblouir I ran `watch -n5 ray status` on one of the compute nodes while the example was running and a sample of the output is given below. For this job I allocated 8 nodes with 4 GPUs (V100) each. From the output we can see all of the 32 GPUs---but the usage of all resources remained at zero for the entirety of the execution.

> It looks like the profiling is trying to create more processes than the amount of available logical CPUs on your machine via Ray, resulting in hanging.

Is there a way to run with profiling disable just to see if it works?

I also ran some other (very simple) tests without Alpa where I launch a bunch of tasks or actors and it seems to be running fine.

```
======== Autoscaler status: 2023-03-13 11:34:48.020321 ========                                                                                                                                                                                
Node status                                                                                                                                                                                                                                    
---------------------------------------------------------------                                                                                                                                                                                
Healthy:                                                                                                                                                                                                                                       
 1 node_4ea936f8a79487627b429676dfeeee82d8aa951396450e81fccbde70                                                                                                                                                                               
 1 node_2bb257a71e82b39a12488c7414f21cbb08ebf7073398b2cd84eaa15d                                                                                                                                                                               
 1 node_64fcc89dee05bf7e5bee0fe51ffc1bd919a108eebdd4b2dbb8e7b9af                                                                                                                                                                               
 1 node_88755f5a51ebbdb856854b1f4ef82806a561eb8a008d038cbbe72a33                                                                                                                                                                               
 1 node_03789627b3f61992abf6a807bbd186490c03838e71293f9018f71e0e                                                                                                                                                                               
 1 node_157f908f31caa76661eeb887e7c0ac9f6cebf09e8f1616a3ab0a2958                                                                                                                                                                               
 1 node_836d00c494cd05dbbff7136ee2b893bbd49fdcfe59cb67fb6642517d                                                                                                                                                                               
 1 node_5deb78ca652a15ea1afc08b720ecbe01bacbdf5929b40772a3bc1874                                                                                                                                                                               
Pending:                                                                                                                                                                                                                                       
 (no pending nodes)                                                                                                                                                                                                                            
Recent failures:                                                                                                                                                                                                                               
 (no failures)                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                               
Resources                                                                                                                                                                                                                                      
---------------------------------------------------------------                                                                                                                                                                                
Usage:                                                                                                                                                                                                                                         
 0.0/8.0 CPU (0.0 used of 8.0 reserved in placement groups)                                                                                                                                                                                    
 0.0/32.0 GPU (0.0 used of 32.0 reserved in placement groups)                                                                                                                                                                                  
 0.0/8.0 accelerator_type:V100                                                                                                                                                                                                                 
 0.00/2078.250 GiB memory                                                                                                                                                                                                                      
 0.00/894.670 GiB object_store_memory                                                                                                                                                                                                          
                                                                                                                                                                                                                                               
Demands:                                                                                                                                                                                                                                       
 {'CPU': 1.0}: 2+ pending tasks/actors
```

**Comment by leiteg** [comment]
I finally found the problem. The Slurm script I posted above was taken from the documentation page [Using Alpa on Slurm](https://alpa.ai/tutorials/alpa_on_slurm.html) and it defines the `sbatch` flag `--cpus-per-task=1`. This made only one core available per Ray process, causing Alpa to hang during the distributed compilation of the model due to the lack of CPU resources available for scheduling.

The solution consisted in not specifying the amount of CPUs per task in the `sbatch` script and let the Ray process use all of the CPUs and GPUs available (which is the default behavior).

To my understanding, the example in the documentation is incorrect. Should I send a patch to fix it?

```diff
--- a.sh	2023-03-15 10:53:58.315148470 -0300
+++ b.sh	2023-03-15 10:54:24.661178461 -0300
@@ -2,14 +2,13 @@
 #SBATCH --partition=GPU
 #SBATCH --nodes=2
 #SBATCH --tasks-per-node=1
-#SBATCH --cpus-per-task=1
 #SBATCH --mem-per-cpu=1GB
 #SBATCH --gpus-per-node=v100-16:8
 #SBATCH --time=00:10:00

 # ...[snip]...
 
 srun --nodes=1 --ntasks=1 -w "$head_node" \
         ray start --head --node-ip-address="$head_node_ip" --port=$port \
-        --num-cpus "${SLURM_CPUS_PER_TASK}" --num-gpus $gpus_per_node --block &
+        --block &

 # ...[snip]...
 
 worker_num=$((SLURM_JOB_NUM_NODES - 1))
 
@@ -17,7 +16,6 @@
     node_i=${nodes_array[$i]}
     echo "Starting WORKER $i at $node_i"
     srun --nodes=1 --ntasks=1 -w "$node_i" \
-        ray start --address "$ip_head" --num-cpus "${SLURM_CPUS_PER_TASK}" \
-        --num-gpus $gpus_per_node --block &
+        ray start --address "$ip_head" --block &
     sleep 5
 done

```
