### ISSUE TITLE
Unable to use pipeline parallelism with multi-node meshes

### ISSUE THREAD

**Issue by Edwinhe03** [alpa-projects/alpa#953]
**Please describe the bug**
Using `benchmark/alpa/suite_manual_gpt.py` to configure benchmark cases with varying (Data, Operator, Pipeline) parallelism. When `PP degree > 1 && DP degree * OP degree > # GPUs per node`, the pipeshard parallel executable fails to compile. For example, setting `DP=4, OP=4, PP=2` on 4 nodes with 8 GPUs each. In this case, the logical mesh shape is `[(4, 4)] * 2`, and the physical mesh shape is `[(2, 8)] * 2` indicating it is multi-node. However, it does not appear to be able to access all the GPUs on different machines. This problem only occurs when pipeline parallelism is enabled (PP > 1).
```
F external/org_tensorflow/tensorflow/tsl/platform/statusor.cc:33] Attempting to fetch value instead of handling error INVALID_ARGUMENT: No matching device found for local_hardware_id 8
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/alpa/benchmark/alpa/benchmark_one_case.py", line 76, in benchmark_and_write_to_namespace
    result = benchmark_one_case_internal(*args, **kwargs)
  File "/alpa/benchmark/alpa/benchmark_one_case.py", line 62, in benchmark_one_case_internal
    result = benchmark_gpt_bert_3d_internal(
  File "/alpa/benchmark/alpa/benchmark_one_case_gpt_bert.py", line 240, in benchmark_gpt_bert_3d_internal
    executable) = compile_and_benchmark_pipeshard_training_executable(
  File "/alpa/benchmark/alpa/benchmark_parallel_utils.py", line 359, in compile_and_benchmark_pipeshard_training_executable
    executable, compilation_times = compile_pipeshard_executable(
  File "/alpa/benchmark/alpa/benchmark_parallel_utils.py", line 307, in compile_pipeshard_executable
    executable = train_step.get_executable(state, *other_train_step_inputs)
  File "/alpa/alpa/api.py", line 135, in get_executable
    executable, _, _, _ = self._decode_args_and_get_executable(*args)
  File "/alpa/alpa/api.py", line 199, in _decode_args_and_get_executable
    executable = _compile_parallel_executable(f, in_tree, out_tree_hashable,
  File "/opt/conda/lib/python3.10/site-packages/jax/linear_util.py", line 309, in memoized_fun
    ans = call(fun, *args)
  File "/alpa/alpa/api.py", line 231, in _compile_parallel_executable
    return method.compile_executable(fun, in_tree, out_tree_thunk,
  File "/alpa/alpa/parallel_method.py", line 240, in compile_executable
    return compile_pipeshard_executable(
  File "/alpa/alpa/pipeline_parallel/compile_executable.py", line 117, in compile_pipeshard_executable
    executable = PipeshardDriverExecutable(
  File "/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 97, in __init__
    self._instantiate_nccl_groups(pipeshard_config.device_str_groups)
  File "/alpa/alpa/pipeline_parallel/pipeshard_executable.py", line 141, in _instantiate_nccl_groups
    self.mesh_group.instantiate_nccl_group(i, j)
  File "/alpa/alpa/device_mesh.py", line 2022, in instantiate_nccl_group
    self._instantiate_nccl_group(cg)
  File "/alpa/alpa/device_mesh.py", line 2123, in _instantiate_nccl_group
    cg.instantiate_now()
  File "/alpa/alpa/pipeline_parallel/cross_mesh_resharding.py", line 650, in instantiate_now
    ray.get(task_dones)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/ray/_private/worker.py", line 2495, in get
    raise value
```

**Please describe the expected behavior**
Pipeshard parallelism should work with `PP degree > 1 && DP * OP degree > # GPUs per node`, like in the example mentioned above.

**System information and environment**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, docker): Linux Ubuntu 20.04
- Python version: 3.10
- CUDA version: 11.8
- NCCL version: 2.17.1
- cupy version: cupy-cuda11x
- GPU model and memory: A100 80GB (8 per node)
- Alpa version: head (852d632ab890bce4876bfcbc8f54313110e84d1d)

**To Reproduce**
1. Follow steps in `benchmark/alpa/README.md` to launch Ray cluster
2. Add failing benchmark case to `benchmark/alpa/suite_manual_gpt.py` (see below)
3. Run `python benchmark/alpa/benchmark.py --suite gpt.tmp`

**Code snippet to reproduce the problem**
Add the following benchmark case to `benchmark/alpa/suite_manual_gpt.py`
See comments in this file for meaning of each argument.
```
tmp_suite = {
    32: [
        BenchmarkCase(32, GPTModelConfig(2048, 2048, 48, 32, 51200), 1, "uniform", UniformParallelArgs(True, True, 4, 4, 2, True))
    ],
}
```

**Additional information**
Notation: (data parallelism degree, operator parallelism degree, pipeline parallelism degree)
The following configurations compile:
`(1, 8, 4), (2, 4, 4), (4, 2, 4), (8, 1, 4), (4, 8, 1), (8, 4, 1), (16, 2, 1)`
The following configurations do not compile:
`(4, 4, 2), (2, 8, 2), (8, 2, 2)`

**Comment by Edwinhe03** [comment]
Fixed after pulling latest commit of tensorflow-alpa submodule: https://github.com/alpa-projects/tensorflow-alpa/commit/c079cc2805a0c3ba57be8eb5e4bf95840bd6e08b
